#!/usr/bin/env bash
#
# G5.c helper — capture the cluster's CoS class set and emit a
# class=DSCP map suitable for g5-smoke-cos-on.sh.
#
# Strategy:
#   1. Run `show class-of-service classifier` on the RG0 primary to
#      enumerate configured forwarding classes.
#   2. Run `show class-of-service code-point-aliases dscp` to pull
#      the alias→DSCP-decimal map.
#   3. Cross-reference and emit "class=<dscp-decimal>" lines into
#      cos-dscp-map.txt.
#
# Fallback: if classifier output is unparseable (unexpected format
# drift), the script emits a documented default for the standard four
# classes — best-effort, assured-forwarding, expedited-forwarding,
# network-control — using IANA DSCP defaults. This keeps Phase B
# moving; the operator can edit cos-dscp-map.txt and rerun.
#
# Writes:
#   artifacts/cos-classifier-fw0.txt
#   artifacts/cos-aliases-fw0.txt
#   artifacts/cos-dscp-map.txt
#
# CALLER must hold cluster access lock via smoke-runner singleton.

set -uo pipefail

ART_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/artifacts
mkdir -p "$ART_DIR"

NODE=${NODE:-loss:xpf-userspace-fw0}
MAP="$ART_DIR/cos-dscp-map.txt"

sg incus-admin -c "incus exec $NODE -- cli -c 'show class-of-service classifier'" \
    > "$ART_DIR/cos-classifier-fw0.txt" 2>&1 || true
sg incus-admin -c "incus exec $NODE -- cli -c 'show class-of-service code-point-aliases dscp'" \
    > "$ART_DIR/cos-aliases-fw0.txt" 2>&1 || true

# Attempt to extract forwarding-class names from the classifier
# output. Junos-style classifiers print "Forwarding class <name>"
# lines or class names in a table column. Be liberal in what we
# accept.
mapfile -t CLASSES < <(awk '
    /[Ff]orwarding[ -]class/ { for(i=1;i<=NF;i++) if($i ~ /^[a-z][a-z0-9_-]*$/) print $i }
' "$ART_DIR/cos-classifier-fw0.txt" | sort -u || true)

# IANA DSCP defaults used as fallback / cross-reference. Decimal
# values match the iperf3 --tos field (which takes a TOS byte, not
# DSCP — but Linux iperf3 accepts decimal in either interpretation
# and the kernel masks ECN; passing DSCP<<2 is the canonical form).
declare -A DEFAULT_DSCP=(
    [best-effort]=0
    [assured-forwarding]=72        # AF21 = 18 << 2
    [expedited-forwarding]=184     # EF   = 46 << 2
    [network-control]=224          # CS7  = 56 << 2
    [voice]=184                    # alias for EF
    [video]=136                    # AF41 = 34 << 2
)

: > "$MAP"
echo "# Generated by g5-capture-cos-map.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$MAP"
echo "# Format: class=<iperf3 --tos decimal>" >> "$MAP"
echo "# Override at will; g5-smoke-cos-on.sh reads class=value lines." >> "$MAP"

emit_class() {
    local c="$1"
    local d="${DEFAULT_DSCP[$c]:-}"
    if [[ -z "$d" ]]; then
        echo "# class $c had no DSCP default — please fill in" >> "$MAP"
        echo "$c=0" >> "$MAP"
        echo "g5-cos-map: WARN — unknown class $c, defaulted to TOS 0"
    else
        echo "$c=$d" >> "$MAP"
        echo "g5-cos-map: $c -> TOS $d"
    fi
}

if [[ "${#CLASSES[@]}" -eq 0 ]]; then
    echo "g5-cos-map: WARN — classifier output unparseable, falling back to defaults"
    for c in best-effort assured-forwarding expedited-forwarding network-control; do
        emit_class "$c"
    done
else
    for c in "${CLASSES[@]}"; do
        emit_class "$c"
    done
fi

echo "g5-cos-map: wrote $MAP"
cat "$MAP"
