package daemon

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/netip"
	"os"
	"os/exec"
	"sort"
	"strings"
	"time"

	"golang.org/x/sys/unix"

	"github.com/psaab/xpf/pkg/config"
	"github.com/psaab/xpf/pkg/daemon/system"
	"github.com/psaab/xpf/pkg/dhcp"
	"github.com/psaab/xpf/pkg/fsatomic"
)

// isCrossDeviceOrBusy reports whether err is an EXDEV/EBUSY from rename(2)
// onto /etc/resolv.conf — the symptom of /etc/resolv.conf being a bind
// mount (common in CI/containers), where an atomic rename onto the mount
// point is not permitted and an in-place write is the only option.
func isCrossDeviceOrBusy(err error) bool {
	return errors.Is(err, unix.EXDEV) || errors.Is(err, unix.EBUSY)
}

// DNS ownership (#1715)
//
// xpf owns /etc/resolv.conf as a managed plain file. systemd-resolved is
// deterministically disabled + masked; the legacy bpfrx.conf drop-in is
// removed. A single reconcileDNS is the only writer of /etc/resolv.conf,
// merging static `system name-server` config with DHCP-learned
// nameservers from every live lease (v4 + v6). It runs at startup, on
// every config apply, and on every DHCP address change.
//
// This replaces the prior three-owner straddle (applySystemDNS wrote a
// resolved drop-in + restarted resolved; applyDNSService disabled
// resolved two lines later — a self-inflicted apply-order race that left
// /etc/resolv.conf a dangling symlink; the DHCP installDNS path wrote
// the file through that symlink and failed silently). See
// docs/dns-ownership.md.

const (
	resolvConfPath = "/etc/resolv.conf"
	// legacyResolvedDropin is the stale pre-rename drop-in
	// (`# Generated by bpfrxd`). Current code only writes/removes
	// xpf.conf; nothing ever removed bpfrx.conf. Inert while resolved is
	// off, but it would double-apply DNS= if resolved were ever the
	// owner, so the reconciler removes it.
	legacyResolvedDropin = "/etc/systemd/resolved.conf.d/bpfrx.conf"
	// xpfResolvedDropin is the drop-in the old applySystemDNS wrote.
	// With xpf owning resolv.conf directly and resolved masked, it is
	// dead; remove it so a future operator unmask of resolved does not
	// resurrect a second owner.
	xpfResolvedDropin = "/etc/systemd/resolved.conf.d/xpf.conf"
)

// dnsReconciler performs the filesystem + systemd side of DNS ownership.
// Paths and systemd ops are fields so unit tests can target a tempdir
// and stub the service calls; production uses newDNSReconciler().
type dnsReconciler struct {
	resolvConfPath       string
	legacyResolvedDropin string
	xpfResolvedDropin    string
	// disableMaskResolved disables + masks systemd-resolved. Returns an
	// error on failure so the reconciler does NOT assume resolved is off
	// (a still-running resolved would be a second owner). Stubbed in
	// tests.
	disableMaskResolved func() error
}

// newDNSReconcilerFn is the constructor reconcileDNSLocked uses. It is a
// package var only so a test can point that path at a tempdir and read the
// file the reconcile ACTUALLY writes (#9138). Without it the last edge —
// reconcileDNSLocked handing dnsInputLocked's result to the reconciler —
// could be severed with the Go suite green: the merge policy is covered
// against mergeDNSInput, the filesystem behaviour against a hand-built
// dnsReconciler (#6792), and nothing joined the two.
var newDNSReconcilerFn = newDNSReconciler

func newDNSReconciler() *dnsReconciler {
	return &dnsReconciler{
		resolvConfPath:       resolvConfPath,
		legacyResolvedDropin: legacyResolvedDropin,
		xpfResolvedDropin:    xpfResolvedDropin,
		disableMaskResolved:  disableMaskResolved,
	}
}

// validLeaseDNSServer reports whether a DHCP-learned DNS server address may
// be installed as the host's own resolver (#10857). Only global-unicast
// addresses are usable there: multicast (ff02::1), loopback (::1),
// link-local (fe80::1 — zoneless and unusable from the host context) and
// unspecified addresses are dropped. netip's IsGlobalUnicast still returns
// true for IPv4 private space and IPv6 ULA, so LAN resolvers (192.168.x.x,
// fd00::/8) keep working. Static `system name-server` entries are NOT gated
// here — loopback-for-local-resolver stays a product decision on that path.
func validLeaseDNSServer(ip netip.Addr) bool {
	return ip.IsValid() && ip.IsGlobalUnicast()
}

// mergeDNSInput builds the renderer input from static config plus the
// DHCP leases the manager currently holds. Precedence: static
// `system name-server` first, then DHCPv4, then DHCPv6, de-duplicated
// (static is authoritative; DHCP augments, never overrides).
//
// ROUTING-INSTANCE SCOPING (#9138). A lease learned on an interface that
// belongs to a routing instance does NOT contribute. /etc/resolv.conf is the
// whole resolver for this host (systemd-resolved is masked) and the host
// resolves from the DEFAULT routing context, so a nameserver reachable only
// inside a tenant VRF is a DEAD entry there: every lookup that reaches it
// burns a full resolver timeout before falling through. That is the certain
// cost. The reason the dimension is worth a filter rather than a note is the
// other one: DHCP is the only path by which a network the firewall does not
// trust writes into the firewall's own host configuration, and a routing
// instance is the operator saying that network is separate. What the host
// resolves is bounded but not nothing — NTP peers, syslog and
// archival-transfer destinations, DDNS update servers, and the IPsec
// dynamic-hostname family hint.
//
// The filter derives from dhcpLeaseRoutingInstances (daemon_flow.go), the
// SAME authority collectDHCPRoutes uses to tag a route with its instance, so
// the two lease consumers cannot answer the same question differently — and
// so this one inherits the #9135 key-shape rule instead of re-deriving it
// (a filter keyed on the raw config token would be inert for the canonical
// Junos slash spelling, exactly as the #8963 remedy was).
//
// Two things this deliberately does NOT do:
//
//   - It does not exclude "anything in a VRF". fxp0 and the other management
//     interfaces live in the synthesized mgmt VRF, which is NOT a routing
//     instance; excluding by VRF membership would take bootstrap DNS with it.
//     The predicate is routing-instance membership, and mgmt interfaces are
//     absent from that map unless an operator explicitly puts them there.
//   - It does not touch the default context. A DHCP client on a WAN link in
//     the default instance still contributes, which is the supported CPE
//     deployment and matches Junos, where DHCP-learned DNS is global.
//
// An operator who leaks the instance's routes into the default table and
// genuinely wants that resolver names it with `system name-server`, which is
// listed first and is already documented as authoritative.
//
// Lease lifecycle note: dhcp.Leases() reflects the manager's held leases.
// A lease is dropped (and thus stops contributing DNS) when its client is
// stopped or the interface is deconfigured; on a transient
// renewal/rebind failure the manager intentionally keeps the last lease
// and keeps using its address until a fresh DORA succeeds, so its DNS is
// retained too — matching the address it is still bound to (a firewall
// must not blackhole its own management resolver mid-renewal). DNS only
// truly clears when no held lease and no static name-server remain.
// domain-name / domain-search come from
// static config only (DHCP domain options are not consumed here).
func mergeDNSInput(cfg *config.Config, leases []*dhcp.Lease) system.ResolvedDropinInput {
	seen := make(map[string]struct{})
	var servers []string
	add := func(s string) {
		if s == "" {
			return
		}
		if _, dup := seen[s]; dup {
			return
		}
		seen[s] = struct{}{}
		servers = append(servers, s)
	}

	if cfg != nil {
		// #5010 render belt: name-server is rendered verbatim into the
		// resolv.conf `nameserver` line and the resolved.conf `DNS=` line.
		// The strict commit gate (config.ValidateIPAddress on the leaf)
		// rejects a malformed value, but #1960 downgrades that to a warning
		// on the tolerant load / peer-sync path — so re-validate each static
		// name-server here and fail-closed skip a value that is not a bare IP
		// address (an embedded space would inject a second resolver token).
		// This mirrors the domain-name / domain-search belt below (#4902).
		// The DHCP-learned servers appended after this loop are
		// netip.Addr.String() output (no render injection), but they still
		// need CLASS validation at the append site below (#10857): a rogue
		// server can supply multicast, loopback, link-local or unspecified
		// resolvers without any bad leased address — a DNS-only hijack of
		// host resolution, retained across transient renew failures.
		for _, ns := range cfg.System.NameServers {
			if err := config.ValidateIPAddress(ns, nil); err != nil {
				slog.Warn("skipping invalid name-server", "server", ns, "err", err)
				continue
			}
			add(ns)
		}
	}
	// DHCPv4 leases first, then DHCPv6. Within a family, leases are
	// sorted by interface name so the merge is deterministic regardless
	// of dhcp.Leases() map-iteration order — otherwise resolver priority
	// (and the byte-for-byte idempotence compare) would flap when two
	// interfaces in the same family both learn DNS.
	sorted := make([]*dhcp.Lease, 0, len(leases))
	for _, l := range leases {
		if l != nil {
			sorted = append(sorted, l)
		}
	}
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Interface < sorted[j].Interface
	})
	// #9138: the routing instance each lease's interface belongs to, from the
	// shared authority (see the ROUTING-INSTANCE SCOPING note above).
	leaseInstance := dhcpLeaseRoutingInstances(cfg)
	for _, fam := range []dhcp.AddressFamily{dhcp.AFInet, dhcp.AFInet6} {
		for _, l := range sorted {
			if l.Family != fam {
				continue
			}
			if ri := leaseInstance[l.Interface]; ri != "" {
				slog.Debug("DNS: skipping DHCP-learned nameservers from a "+
					"routing-instance interface (unreachable from the default "+
					"resolver context)",
					"interface", l.Interface, "instance", ri, "count", len(l.DNS))
				continue
			}
			for _, ip := range l.DNS {
				if !validLeaseDNSServer(ip) {
					slog.Warn("skipping non-global-unicast DHCP name-server",
						"interface", l.Interface, "server", ip.String())
					continue
				}
				add(ip.String())
			}
		}
	}

	in := system.ResolvedDropinInput{NameServers: servers}
	if cfg != nil {
		// #4902 render belt: domain-name / domain-search are rendered verbatim
		// into the resolved.conf `Domains=` line and the resolv.conf `search`
		// line. Drop a leniently-loaded / peer-synced value that is not a valid
		// DNS name (an embedded space would inject an extra resolver token). The
		// strict commit gate (config.ValidateDNSDomain) rejects it at commit.
		if config.ValidateDNSDomain(cfg.System.DomainName, nil) == nil {
			in.DomainName = cfg.System.DomainName
		} else if cfg.System.DomainName != "" {
			slog.Warn("skipping invalid domain-name", "domain", cfg.System.DomainName)
		}
		for _, d := range cfg.System.DomainSearch {
			if config.ValidateDNSDomain(d, nil) == nil {
				in.DomainSearch = append(in.DomainSearch, d)
			} else {
				slog.Warn("skipping invalid domain-search entry", "domain", d)
			}
		}
	}
	return in
}

// reconcile renders the merged input and reconciles /etc/resolv.conf as a
// managed plain file, removes stale resolved drop-ins, and disables +
// masks systemd-resolved.
//
// bootEmptyRepairOnly selects the §5b.4 boot policy: when true (first
// startup apply, before any DHCP lease) and there are NO nameservers to
// install (a search-only render is not a usable resolver), an existing
// non-dangling regular /etc/resolv.conf is left untouched — only a
// dangling / symlinked / missing file is repaired. The guard keys off
// the nameserver set (not in.Empty()) so a config carrying only
// domain-name/domain-search with no static name-server and no lease does
// not blank a good resolver file at boot. When false (an explicit
// runtime commit or a DHCP change), a no-nameserver render is a
// declarative "clear DNS" and the managed file is written so removing
// all name-servers / expiring the last lease actually clears the
// resolver instead of leaking stale servers.
func (r *dnsReconciler) reconcile(in system.ResolvedDropinInput, bootEmptyRepairOnly bool) error {
	// #6792: every failure below is ACCUMULATED and returned rather than left
	// at WARN. Each one leaves the host in a resolver state the operator did
	// not ask for — a live systemd-resolved alongside xpf's managed file (and
	// xpf's own networkd .network files carry UseDNS=yes, so a surviving
	// resolved is independently fed DHCP nameservers), or a stale
	// /etc/resolv.conf whose write failed AFTER the mask and drop-in removal
	// already ran. A commit reported success either way, and there is no
	// retry, no ticker and no metric behind it.
	//
	// Accumulate rather than return early: the pre-#6792 control flow is
	// deliberate — a mask failure still writes resolv.conf, because a static
	// file wins over an inactive stub — and returning at the first failure
	// would make a systemd hiccup ALSO skip the resolver write. So the
	// sequence is unchanged; only its reporting is.
	var errs []error

	// Always converge resolved off + remove stale drop-ins, regardless of
	// whether resolv.conf needs rewriting, so a previously-installed
	// drop-in / running resolved is cleaned up even on an idempotent pass.
	if err := r.disableMaskResolved(); err != nil {
		// Do NOT proceed assuming resolved is off — it would be a second
		// owner. Still own resolv.conf (a static file wins over an
		// inactive stub), but surface the failure loudly.
		slog.Warn("DNS: failed to disable+mask systemd-resolved; it may remain a second resolver owner", "err", err)
		errs = append(errs, fmt.Errorf("disable+mask systemd-resolved: %w", err))
	}
	for _, p := range []string{r.legacyResolvedDropin, r.xpfResolvedDropin} {
		if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
			slog.Warn("DNS: failed to remove stale resolved drop-in", "path", p, "err", err)
			errs = append(errs, fmt.Errorf("remove stale resolved drop-in %s: %w", p, err))
		}
	}

	content := system.RenderResolvConf(in)

	// Inspect the current target without following symlinks.
	fi, lerr := os.Lstat(r.resolvConfPath)
	isSymlink := lerr == nil && fi.Mode()&os.ModeSymlink != 0
	missing := os.IsNotExist(lerr)

	// Boot empty-merge policy: no nameservers to install and a good
	// regular file already exists → repair only a bad (symlink/missing)
	// target, never clobber a good file. A symlink (e.g. the dangling
	// stub) or a missing file IS repaired below by writing the managed
	// file. Keyed on the nameserver set, not in.Empty(), so a
	// domain-name/domain-search-only config does not blank a good file.
	if len(in.NameServers) == 0 && bootEmptyRepairOnly && !isSymlink && !missing && lerr == nil {
		return errors.Join(errs...)
	}

	// Idempotence: if the target is already a regular file with identical
	// content, skip the rewrite (and the restart churn it would imply).
	if !isSymlink && lerr == nil {
		if cur, err := os.ReadFile(r.resolvConfPath); err == nil && string(cur) == content {
			return errors.Join(errs...)
		}
	}

	if err := r.atomicWrite(content); err != nil {
		slog.Warn("DNS: failed to write managed /etc/resolv.conf", "path", r.resolvConfPath, "err", err)
		errs = append(errs, fmt.Errorf("write managed %s: %w", r.resolvConfPath, err))
		return errors.Join(errs...)
	}
	slog.Info("DNS: reconciled managed /etc/resolv.conf",
		"servers", in.NameServers, "domain", in.DomainName, "search", in.DomainSearch,
		"replaced_symlink", isSymlink)
	return errors.Join(errs...)
}

// atomicWrite replaces resolvConfPath with content via
// fsatomic.WriteFileAtomic (temp-in-same-dir + rename). rename(2)
// atomically replaces a symlink target WITHOUT following it (fsatomic's
// default, no WithResolveSymlinks), so a dangling/stub symlink is swapped
// for a real file with no ENOENT window and no need to os.Remove the
// symlink first — matching the prior hand-rolled semantics.
//
// On EXDEV/EBUSY (rename across a bind mount, common in CI/containers
// where /etc/resolv.conf is bind-mounted) it falls back to
// writeResolvConfBindMountFallback (in-place write).
func (r *dnsReconciler) atomicWrite(content string) error {
	// AtomicGeneratedConfig (D3): regenerated from declarative DNS config
	// on every apply, so a power-cut loss self-heals. fsatomic's default
	// (no WithResolveSymlinks) renames over the path itself — replacing a
	// symlink with a regular file, matching the prior rename-over-symlink
	// semantics.
	err := fsatomic.WriteFileAtomic(r.resolvConfPath, []byte(content), 0644)
	if err == nil {
		return nil
	}
	// EXDEV/EBUSY (matched through fsatomic's %w wrapping via errors.Is) is
	// the bind-mount symptom: rename onto the mount point is not permitted,
	// so write through in place. This BestEffortKernelKnob-style fallback is
	// the sole allowlisted direct write here.
	if isCrossDeviceOrBusy(err) {
		slog.Warn("DNS: rename onto /etc/resolv.conf failed (likely bind mount); writing in place", "err", err)
		return writeResolvConfBindMountFallback(r.resolvConfPath, content)
	}
	return err
}

// writeResolvConfBindMountFallback writes content to path in place
// (truncate+write), used only when an atomic rename is impossible because
// /etc/resolv.conf is a bind mount (EXDEV/EBUSY). This is the one
// deliberately-direct os.WriteFile in the DNS path — a rename(2) cannot
// replace a bind-mount target, so it is allowlisted in the fsatomic canary.
func writeResolvConfBindMountFallback(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("in-place write fallback: %w", err)
	}
	return nil
}

// disableMaskResolved disables + masks systemd-resolved so neither the
// service nor its socket-activation units (varlink/monitor sockets) can
// re-create the /run/systemd/resolve stub that the base-image symlink
// points at. Masking is sticky across reboots; the unmask path for a
// future resolved-owner mode is documented in docs/dns-ownership.md.
//
// It is idempotent and quiet:
//   - On a systemd-less host (no /run/systemd/system — containers/CI) it
//     is a no-op success; there is no resolved to fight.
//   - When the unit is already `masked` it returns success without
//     re-running systemctl, since `disable --now` on a masked unit fails
//     and would otherwise spam a false "second owner" warning on every
//     commit / DHCP change. Reaching the desired end-state (masked) is
//     the success condition, not a fresh transition.
func disableMaskResolved() error {
	// No systemd → nothing to disable/mask. /run/systemd/system is the
	// canonical "booted with systemd" probe (sd_booted(3)).
	if _, err := os.Stat("/run/systemd/system"); err != nil {
		return nil
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// `systemctl is-enabled` prints a status token (and exits non-zero for
	// masked/not-found); key off the stdout token, not the exit code.
	//   - `masked`: already at the desired end-state — do nothing.
	//   - `not-found`: systemd-resolved is not installed, so it cannot run
	//     as a second resolver owner; nothing to disable/mask. Treating it
	//     as success avoids a spurious "second owner" warning on every
	//     reconcile on minimal installs that lack the resolved package.
	isEnabledCmd := exec.CommandContext(ctx, "systemctl", "is-enabled", "systemd-resolved.service")
	isEnabledCmd.WaitDelay = 5 * time.Second // post-SIGKILL pipe-drain cap (#1794)
	out, _ := isEnabledCmd.CombinedOutput()
	switch strings.TrimSpace(string(out)) {
	case "masked", "not-found":
		return nil
	}

	disableCmd := exec.CommandContext(ctx, "systemctl", "disable", "--now", "systemd-resolved.service")
	disableCmd.WaitDelay = 5 * time.Second
	if out, err := disableCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("disable --now systemd-resolved: %w (%s)", err, string(out))
	}
	maskCmd := exec.CommandContext(ctx, "systemctl", "mask", "systemd-resolved.service")
	maskCmd.WaitDelay = 5 * time.Second
	if out, err := maskCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("mask systemd-resolved: %w (%s)", err, string(out))
	}
	return nil
}

// reconcileDNSLocked renders + reconciles DNS. It MUST be called with
// d.applySem held (it is invoked from applyConfigLocked). It must NOT
// re-acquire applySem (deadlock) — i.e. it must not call applyConfig or
// reconcileDNSFromDHCP.
//
// bootEmptyRepairOnly is set by the early-boot apply (before DHCP clients
// start) so an empty merge does not blank a pre-existing good file; a
// later commit / DHCP change passes false so clearing DNS truly clears
// the file.
func (d *Daemon) reconcileDNSLocked(cfg *config.Config, bootEmptyRepairOnly bool) error {
	// #6792: test seam. The reconcile's own failures are covered directly
	// against a dnsReconciler; this exists so a test can drive the REAL
	// applyTailReconciles and prove the error actually reaches the commit
	// result — the wiring the per-function cells cannot see.
	if d.reconcileDNSFn != nil {
		return d.reconcileDNSFn(cfg, bootEmptyRepairOnly)
	}
	return newDNSReconcilerFn().reconcile(d.dnsInputLocked(cfg), bootEmptyRepairOnly)
}

// dnsInputLocked joins the committed config with the DHCP manager's CURRENT
// lease set and merges them into the renderer input. Same locking contract as
// its only caller, reconcileDNSLocked.
//
// Split out (#9138) because the join was unobservable: severing the
// `d.dhcp.Leases()` read killed no test in this package, so DHCP-learned DNS
// could stop reaching /etc/resolv.conf entirely with the Go suite green. The
// merge policy itself is covered against mergeDNSInput, and the filesystem
// side against a dnsReconciler with tempdir paths (#6792); this is the seam
// between them, and it is the one that had no cell.
func (d *Daemon) dnsInputLocked(cfg *config.Config) system.ResolvedDropinInput {
	var leases []*dhcp.Lease
	if d.dhcp != nil {
		leases = d.dhcp.Leases()
	}
	return mergeDNSInput(cfg, leases)
}

// reconcileDNSFromDHCP is the DHCP-callback entry point. It acquires
// applySem once, reads the active config, and reconciles DNS with the
// current lease set. This is the path that fixes the fw0 class: a
// management-only interface (fxp0) DHCP change reaches DNS reconcile even
// though it does not trigger a dataplane recompile.
//
// It passes bootEmptyRepairOnly=false: a DHCP change is a live event, and
// if it ever produces an empty merge (last lease expired, no static
// name-server) that is a real "clear DNS".
func (d *Daemon) reconcileDNSFromDHCP() {
	if err := d.applySem.Acquire(context.Background(), 1); err != nil {
		slog.Warn("DNS: failed to acquire apply lock for DHCP reconcile", "err", err)
		return
	}
	defer d.applySem.Release(1)
	cfg := d.store.ActiveConfig()
	// #6792: no commit to fail here — this is a lease-change callback, not an
	// operator action — so the failure is logged rather than returned. It is
	// logged at WARN with the same wording the commit path surfaces, because
	// the end state is identical (a second resolver owner, or a stale
	// resolv.conf) and an operator reading the log after a DHCP change needs
	// the same signal a commit would have given them. The next commit or lease
	// change re-drives the reconcile, which is idempotent.
	if err := d.reconcileDNSLocked(cfg, false); err != nil {
		slog.Warn("DNS: reconcile after a DHCP change did not reach the "+
			"declared resolver state", "err", err)
	}
}
