package daemon

import (
	"net/netip"
	"os"
	"path/filepath"
	"testing"

	"github.com/psaab/xpf/pkg/config"
	"github.com/psaab/xpf/pkg/daemon/system"
	"github.com/psaab/xpf/pkg/dhcp"
)

const resolvHeader = "# Generated by xpfd — do not edit\n"

// newTestReconciler builds a dnsReconciler that targets a tempdir and
// records (rather than executes) the resolved disable+mask op, so tests
// never touch real /etc or systemctl.
func newTestReconciler(t *testing.T, dir string) (*dnsReconciler, *int) {
	t.Helper()
	maskCalls := 0
	return &dnsReconciler{
		resolvConfPath:       filepath.Join(dir, "resolv.conf"),
		legacyResolvedDropin: filepath.Join(dir, "bpfrx.conf"),
		xpfResolvedDropin:    filepath.Join(dir, "xpf.conf"),
		disableMaskResolved: func() error {
			maskCalls++
			return nil
		},
	}, &maskCalls
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}

func mustLstat(t *testing.T, path string) os.FileInfo {
	t.Helper()
	fi, err := os.Lstat(path)
	if err != nil {
		t.Fatalf("lstat %s: %v", path, err)
	}
	return fi
}

func TestReconcileReplacesDanglingSymlink(t *testing.T) {
	dir := t.TempDir()
	r, mask := newTestReconciler(t, dir)
	// Dangling symlink, like the base-image resolv.conf → resolved stub
	// with resolved off.
	if err := os.Symlink(filepath.Join(dir, "nonexistent", "stub-resolv.conf"), r.resolvConfPath); err != nil {
		t.Fatal(err)
	}

	in := system.ResolvedDropinInput{NameServers: []string{"1.1.1.1"}}
	r.reconcile(in, false)

	fi := mustLstat(t, r.resolvConfPath)
	if fi.Mode()&os.ModeSymlink != 0 {
		t.Fatal("resolv.conf should be a regular file, still a symlink")
	}
	want := resolvHeader + "nameserver 1.1.1.1\n"
	if got := readFile(t, r.resolvConfPath); got != want {
		t.Fatalf("content = %q, want %q", got, want)
	}
	if *mask == 0 {
		t.Fatal("expected disableMaskResolved to be called")
	}
}

func TestReconcileReplacesResolvedStubSymlink(t *testing.T) {
	dir := t.TempDir()
	r, _ := newTestReconciler(t, dir)
	// A non-dangling symlink to a stub file (resolved stub present).
	stub := filepath.Join(dir, "stub-resolv.conf")
	if err := os.WriteFile(stub, []byte("nameserver 127.0.0.53\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(stub, r.resolvConfPath); err != nil {
		t.Fatal(err)
	}

	in := system.ResolvedDropinInput{NameServers: []string{"9.9.9.9"}}
	r.reconcile(in, false)

	if mustLstat(t, r.resolvConfPath).Mode()&os.ModeSymlink != 0 {
		t.Fatal("resolv.conf should be a regular file, still a symlink")
	}
	want := resolvHeader + "nameserver 9.9.9.9\n"
	if got := readFile(t, r.resolvConfPath); got != want {
		t.Fatalf("content = %q, want %q", got, want)
	}
	// The original stub target must be untouched (rename replaces the
	// symlink, never follows it to clobber the stub).
	if got := readFile(t, stub); got != "nameserver 127.0.0.53\n" {
		t.Fatalf("stub target was modified: %q", got)
	}
}

func TestReconcileIdempotentNoRewrite(t *testing.T) {
	dir := t.TempDir()
	r, _ := newTestReconciler(t, dir)
	in := system.ResolvedDropinInput{NameServers: []string{"1.1.1.1", "8.8.8.8"}}
	r.reconcile(in, false)

	fi1 := mustLstat(t, r.resolvConfPath)
	// Second reconcile with identical input must not rewrite the file
	// (mtime unchanged).
	r.reconcile(in, false)
	fi2 := mustLstat(t, r.resolvConfPath)
	if !fi1.ModTime().Equal(fi2.ModTime()) {
		t.Fatalf("expected no rewrite on identical content; mtime changed %v -> %v", fi1.ModTime(), fi2.ModTime())
	}
}

func TestReconcileRewritesOnContentChange(t *testing.T) {
	dir := t.TempDir()
	r, _ := newTestReconciler(t, dir)
	r.reconcile(system.ResolvedDropinInput{NameServers: []string{"1.1.1.1"}}, false)

	r.reconcile(system.ResolvedDropinInput{NameServers: []string{"1.1.1.1", "8.8.8.8"}}, false)
	want := resolvHeader + "nameserver 1.1.1.1\nnameserver 8.8.8.8\n"
	if got := readFile(t, r.resolvConfPath); got != want {
		t.Fatalf("content = %q, want %q", got, want)
	}
}

func TestReconcileEmptyMergeBootRepairsBadButKeepsGoodFile(t *testing.T) {
	// Boot policy: empty merge + good regular file → leave it alone.
	dir := t.TempDir()
	r, _ := newTestReconciler(t, dir)
	good := "# hand-written\nnameserver 1.2.3.4\n"
	if err := os.WriteFile(r.resolvConfPath, []byte(good), 0644); err != nil {
		t.Fatal(err)
	}
	r.reconcile(system.ResolvedDropinInput{}, true /* bootEmptyRepairOnly */)
	if got := readFile(t, r.resolvConfPath); got != good {
		t.Fatalf("good file was clobbered on boot empty-merge: %q", got)
	}

	// But a dangling symlink IS repaired even on boot empty-merge.
	dir2 := t.TempDir()
	r2, _ := newTestReconciler(t, dir2)
	if err := os.Symlink(filepath.Join(dir2, "nope"), r2.resolvConfPath); err != nil {
		t.Fatal(err)
	}
	r2.reconcile(system.ResolvedDropinInput{}, true)
	if mustLstat(t, r2.resolvConfPath).Mode()&os.ModeSymlink != 0 {
		t.Fatal("dangling symlink not repaired on boot empty-merge")
	}
	if got := readFile(t, r2.resolvConfPath); got != resolvHeader {
		t.Fatalf("repaired file = %q, want header-only %q", got, resolvHeader)
	}
}

func TestReconcileEmptyMergeRuntimeClearsFile(t *testing.T) {
	// Post-boot: empty merge is a declarative "clear DNS" — the good
	// file is replaced with the header-only managed file.
	dir := t.TempDir()
	r, _ := newTestReconciler(t, dir)
	if err := os.WriteFile(r.resolvConfPath, []byte("nameserver 1.2.3.4\n"), 0644); err != nil {
		t.Fatal(err)
	}
	r.reconcile(system.ResolvedDropinInput{}, false /* runtime */)
	if got := readFile(t, r.resolvConfPath); got != resolvHeader {
		t.Fatalf("runtime empty-merge did not clear file: %q", got)
	}
}

func TestReconcileRemovesStaleDropins(t *testing.T) {
	dir := t.TempDir()
	r, _ := newTestReconciler(t, dir)
	if err := os.WriteFile(r.legacyResolvedDropin, []byte("# Generated by bpfrxd\nDNS=1.1.1.1\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(r.xpfResolvedDropin, []byte("# Generated by xpfd\nDNS=1.1.1.1\n"), 0644); err != nil {
		t.Fatal(err)
	}
	r.reconcile(system.ResolvedDropinInput{NameServers: []string{"1.1.1.1"}}, false)
	if _, err := os.Stat(r.legacyResolvedDropin); !os.IsNotExist(err) {
		t.Fatalf("legacy bpfrx.conf drop-in not removed: %v", err)
	}
	if _, err := os.Stat(r.xpfResolvedDropin); !os.IsNotExist(err) {
		t.Fatalf("xpf.conf drop-in not removed: %v", err)
	}
}

func TestMergeDNSInputPrecedenceAndDedup(t *testing.T) {
	cfg := &config.Config{}
	cfg.System.NameServers = []string{"1.1.1.1", "8.8.8.8"}
	cfg.System.DomainName = "example.com"
	cfg.System.DomainSearch = []string{"corp.example.com"}

	mk := func(fam dhcp.AddressFamily, addrs ...string) *dhcp.Lease {
		l := &dhcp.Lease{Family: fam}
		for _, a := range addrs {
			l.DNS = append(l.DNS, netip.MustParseAddr(a))
		}
		return l
	}
	leases := []*dhcp.Lease{
		mk(dhcp.AFInet6, "2606:4700:4700::1111"),
		mk(dhcp.AFInet, "8.8.8.8", "9.9.9.9"), // 8.8.8.8 dup of static
	}

	in := mergeDNSInput(cfg, leases)
	want := []string{
		"1.1.1.1", "8.8.8.8", // static first
		"9.9.9.9",              // v4 DHCP (8.8.8.8 de-duped)
		"2606:4700:4700::1111", // v6 DHCP last
	}
	if len(in.NameServers) != len(want) {
		t.Fatalf("servers = %v, want %v", in.NameServers, want)
	}
	for i := range want {
		if in.NameServers[i] != want[i] {
			t.Fatalf("servers[%d] = %q, want %q (full %v)", i, in.NameServers[i], want[i], in.NameServers)
		}
	}
	if in.DomainName != "example.com" || len(in.DomainSearch) != 1 || in.DomainSearch[0] != "corp.example.com" {
		t.Fatalf("domain fields not carried: %+v", in)
	}
}

func TestMergeDNSInputFiltersNonGlobalUnicastLeaseDNS10857(t *testing.T) {
	lease := &dhcp.Lease{
		Interface: "ge-0-0-1",
		Family:    dhcp.AFInet6,
		DNS: []netip.Addr{
			netip.MustParseAddr("ff02::1"),
			netip.MustParseAddr("::1"),
			netip.MustParseAddr("fe80::1"),
			netip.MustParseAddr("2001:4860:4860::8888"),
		},
	}

	in := mergeDNSInput(nil, []*dhcp.Lease{lease})
	want := []string{"2001:4860:4860::8888"}
	if len(in.NameServers) != len(want) || in.NameServers[0] != want[0] {
		t.Fatalf("lease name-servers = %v, want only global-unicast %v", in.NameServers, want)
	}
}

func TestMergeDNSInputNilConfigEmptyLeases(t *testing.T) {
	in := mergeDNSInput(nil, nil)
	if !in.Empty() {
		t.Fatalf("expected empty merge, got %+v", in)
	}
}

// Boot policy must key off the nameserver set, not in.Empty(): a config
// with only domain-name/domain-search (no static name-server, no lease)
// must NOT clobber a good resolv.conf at boot.
func TestReconcileBootDomainOnlyDoesNotClobberGoodFile(t *testing.T) {
	dir := t.TempDir()
	r, _ := newTestReconciler(t, dir)
	good := "# hand-written\nnameserver 1.2.3.4\n"
	if err := os.WriteFile(r.resolvConfPath, []byte(good), 0644); err != nil {
		t.Fatal(err)
	}
	// domain-name set, but no nameservers → search-only render, not a
	// usable resolver. Boot must leave the good file intact.
	in := system.ResolvedDropinInput{DomainName: "example.com", DomainSearch: []string{"corp.example.com"}}
	r.reconcile(in, true /* bootEmptyRepairOnly */)
	if got := readFile(t, r.resolvConfPath); got != good {
		t.Fatalf("boot domain-only merge clobbered good file: %q", got)
	}
}

// Deterministic merge ordering: multiple leases in the same family must
// be sorted by interface name so resolver priority + the idempotence
// compare are stable regardless of dhcp.Leases() map order.
func TestMergeDNSInputDeterministicLeaseOrder(t *testing.T) {
	mk := func(iface string, fam dhcp.AddressFamily, addr string) *dhcp.Lease {
		return &dhcp.Lease{Interface: iface, Family: fam, DNS: []netip.Addr{netip.MustParseAddr(addr)}}
	}
	// Two v4 leases on different interfaces, presented in two opposite
	// orders; merged output must be identical (sorted by interface).
	a := []*dhcp.Lease{mk("ge-0-0-2", dhcp.AFInet, "9.9.9.9"), mk("ge-0-0-1", dhcp.AFInet, "1.1.1.1")}
	b := []*dhcp.Lease{mk("ge-0-0-1", dhcp.AFInet, "1.1.1.1"), mk("ge-0-0-2", dhcp.AFInet, "9.9.9.9")}
	inA := mergeDNSInput(nil, a)
	inB := mergeDNSInput(nil, b)
	want := []string{"1.1.1.1", "9.9.9.9"} // ge-0-0-1 before ge-0-0-2
	for _, in := range []system.ResolvedDropinInput{inA, inB} {
		if len(in.NameServers) != 2 || in.NameServers[0] != want[0] || in.NameServers[1] != want[1] {
			t.Fatalf("non-deterministic / wrong order: %v, want %v", in.NameServers, want)
		}
	}
}
