package daemon

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"golang.org/x/sync/semaphore"

	"github.com/psaab/xpf/pkg/config"
	"github.com/psaab/xpf/pkg/configstore"
	"github.com/psaab/xpf/pkg/dhcpserver"
)

// TestFactoryResetRestoresIdentityAfterFailedWipe10769 is the d05-F6 hostname
// recovery proof: the wipe overwrites the identity files (the seal leg) and a
// LATER leg fails. The failed reset must restore every snapshotted file
// byte-for-byte even though the kernel name already equals the configured
// name — the trap that made the old applyHostname recovery return early and
// leave xpf on disk.
func TestFactoryResetRestoresIdentityAfterFailedWipe10769(t *testing.T) {
	isolateFactoryResetOwnershipPaths(t)
	isolateFactoryResetIdentityPaths(t)
	isolateHandoffFlag(t)
	dir := t.TempDir()
	store, err := configstore.New(filepath.Join(dir, "xpf.conf"))
	if err != nil {
		t.Fatal(err)
	}
	if err := store.EnterConfigure(); err != nil {
		t.Fatal(err)
	}
	if _, err := store.LoadSet("set system host-name tenant-fw\n"); err != nil {
		t.Fatalf("LoadSet: %v", err)
	}
	if _, err := store.Commit(); err != nil {
		t.Fatalf("Commit: %v", err)
	}
	restoreHost := osHostname
	osHostname = func() (string, error) { return "tenant-fw", nil }
	t.Cleanup(func() { osHostname = restoreHost })

	want := map[string]string{
		hostnamePath:        "tenant-fw\n",
		resetHostsPath:      "127.0.0.1 localhost\n127.0.1.1 tenant-fw\n",
		resetResolvConfPath: "# Generated by xpfd — do not edit\nnameserver 192.0.2.53\n",
		resetKnownHostsPath: "# Managed by xpfd — do not edit\nold.example ssh-ed25519 AAAA\n",
	}
	for path, body := range want {
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	d := &Daemon{applySem: semaphore.NewWeighted(1), store: store}
	wipeErr := errors.New("rendered-config leg failed")
	if err := d.factoryReset(context.Background(), func() error {
		for path := range want {
			if err := os.WriteFile(path, []byte("wiped\n"), 0o600); err != nil {
				t.Fatalf("simulate seal overwrite: %v", err)
			}
		}
		return wipeErr
	}); !errors.Is(err, wipeErr) {
		t.Fatalf("factoryReset error = %v, want %v", err, wipeErr)
	}
	for path, body := range want {
		got, err := os.ReadFile(path)
		if err != nil || string(got) != body {
			t.Errorf("identity file %s = %q, want pre-wipe %q (err=%v)", path, got, body, err)
		}
	}
}

// TestFactoryResetSurfacesIdentityRestoreFailure10769 pins that a failed
// identity restore is surfaced, not swallowed: the wipe breaks one restore
// target (replacing the file with a directory) and fails, so the reset error
// must name both the wipe failure and the restore failure.
func TestFactoryResetSurfacesIdentityRestoreFailure10769(t *testing.T) {
	isolateFactoryResetOwnershipPaths(t)
	isolateFactoryResetIdentityPaths(t)
	isolateHandoffFlag(t)
	if err := os.MkdirAll(filepath.Dir(resetHostsPath), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(resetHostsPath, []byte("127.0.0.1 localhost\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	d := &Daemon{applySem: semaphore.NewWeighted(1)}
	wipeErr := errors.New("wipe failed")
	err := d.factoryReset(context.Background(), func() error {
		if err := os.Remove(resetHostsPath); err != nil {
			t.Fatalf("break restore target: %v", err)
		}
		if err := os.MkdirAll(resetHostsPath, 0o700); err != nil {
			t.Fatalf("break restore target: %v", err)
		}
		return wipeErr
	})
	if !errors.Is(err, wipeErr) {
		t.Fatalf("factoryReset error = %v, want %v", err, wipeErr)
	}
	if err == nil || !strings.Contains(err.Error(), "restore") {
		t.Fatalf("factoryReset error must surface the identity restore failure, got %v", err)
	}
}

// TestFactoryResetFailsWhenKeaLeasesReappear10769 pins the post-wipe lease
// re-verification: a wipe that reports success while a lease file is present
// (a writer racing the unlink) must fail the reset closed. The reappeared
// rows are re-erased under the fence before the failure returns — the wipe
// already cleared the pending markers, so leaving them would strand prior
// leases with no boot gate — and a retry converges. The completed wipe's
// fresh identity is NOT rolled back: the config is gone, so the prior
// identity is meaningless.
func TestFactoryResetFailsWhenKeaLeasesReappear10769(t *testing.T) {
	isolateFactoryResetOwnershipPaths(t)
	isolateFactoryResetIdentityPaths(t)
	isolateHandoffFlag(t)
	if err := os.MkdirAll(filepath.Dir(hostnamePath), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(hostnamePath, []byte("tenant-fw\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	lease := resetKeaLeaseCurrents[0] + ".completed"
	d := &Daemon{applySem: semaphore.NewWeighted(1)}
	err := d.factoryReset(context.Background(), func() error {
		if err := os.MkdirAll(filepath.Dir(lease), 0o700); err != nil {
			return err
		}
		if err := os.WriteFile(lease, []byte("recreated lease"), 0o600); err != nil {
			return err
		}
		return os.WriteFile(hostnamePath, []byte("xpf\n"), 0o600)
	})
	if err == nil || !strings.Contains(err.Error(), "reappeared") {
		t.Fatalf("recreated lease must fail the reset, got %v", err)
	}
	if _, serr := os.Lstat(lease); !os.IsNotExist(serr) {
		t.Fatalf("reappeared lease must be re-erased before the failure returns: %v", serr)
	}
	if got, _ := os.ReadFile(hostnamePath); string(got) != "xpf\n" {
		t.Fatalf("completed-wipe identity must stand after a verify failure, got %q", got)
	}
	if err := d.factoryReset(context.Background(), fakePendingWipe(t)); err != nil {
		t.Fatalf("retry after a repaired verify failure must converge: %v", err)
	}
}

type preSeedRecorder10769 struct {
	*recordingDHCPApplier9349
	mu       sync.Mutex
	preSeeds []int
}

func (r *preSeedRecorder10769) PreSeedMemfileMerged4WithAuthority(_ context.Context, _ dhcpserver.LeaseSyncSnapshot, _ time.Time, _ bool, _ dhcpserver.LeaseSyncAuthority) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.preSeeds = append(r.preSeeds, 4)
	return nil
}

func (r *preSeedRecorder10769) PreSeedMemfileMerged6WithAuthority(_ context.Context, _ dhcpserver.LeaseSyncSnapshot, _ time.Time, _ bool, _ dhcpserver.LeaseSyncAuthority) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.preSeeds = append(r.preSeeds, 6)
	return nil
}

func (r *preSeedRecorder10769) count() int {
	r.mu.Lock()
	defer r.mu.Unlock()
	return len(r.preSeeds)
}

// TestPreSeedFencedDuringResetGeneration10769 is the racing-writer regression
// beyond the enqueue path: the VRRP MASTER pre-seed writes the Kea memfile
// directly without holding applySem, so it must observe the reset generation
// itself or re-persist prior leases after their erasure.
func TestPreSeedFencedDuringResetGeneration10769(t *testing.T) {
	d := leaseSyncTestDaemon(t, filepath.Join(t.TempDir(), "x4.sock"), filepath.Join(t.TempDir(), "x6.sock"), true)
	rec := &preSeedRecorder10769{recordingDHCPApplier9349: &recordingDHCPApplier9349{}}
	d.dhcpServer = rec
	d.sessionSync.SetPeerDHCPLeasesForTesting(4, []dhcpserver.SyncLease{{Family: 4, Address: "10.0.61.7", Remaining: 3600}})

	d.preSeedDHCPLeaseMemfile(false)
	if got := rec.count(); got != 1 {
		t.Fatalf("control: pre-seed outside reset wrote %d families, want 1", got)
	}
	d.enterResetGeneration()
	d.preSeedDHCPLeaseMemfile(false)
	if got := rec.count(); got != 1 {
		t.Fatalf("pre-seed during the reset generation must write nothing, total writes = %d", got)
	}
}

// TestPreSeedCrossesResetFence10769 pins that the direct memfile writer
// serializes on the reset fence: while factoryReset holds it across the wipe,
// a pre-seed must wait rather than land mid-wipe. Deterministic in both
// directions: completion while held is impossible when the lock is crossed,
// and immediate completion without it fails RED.
func TestPreSeedCrossesResetFence10769(t *testing.T) {
	d := leaseSyncTestDaemon(t, filepath.Join(t.TempDir(), "x4.sock"), filepath.Join(t.TempDir(), "x6.sock"), true)
	rec := &preSeedRecorder10769{recordingDHCPApplier9349: &recordingDHCPApplier9349{}}
	d.dhcpServer = rec
	d.sessionSync.SetPeerDHCPLeasesForTesting(4, []dhcpserver.SyncLease{{Family: 4, Address: "10.0.61.7", Remaining: 3600}})
	d.ddnsResetMu.Lock()
	done := make(chan struct{})
	go func() {
		d.preSeedDHCPLeaseMemfile(false)
		close(done)
	}()
	select {
	case <-done:
		d.ddnsResetMu.Unlock()
		t.Fatal("pre-seed completed while the reset fence was held; it must serialize on it")
	case <-time.After(100 * time.Millisecond):
	}
	if got := rec.count(); got != 0 {
		d.ddnsResetMu.Unlock()
		t.Fatalf("pre-seed wrote %d families while fenced, want none", got)
	}
	d.ddnsResetMu.Unlock()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("pre-seed did not proceed after the fence released")
	}
	if got := rec.count(); got != 1 {
		t.Fatalf("pre-seed after fence release wrote %d families, want 1", got)
	}
}

// TestReconcileDNSFromDHCPFencedDuringReset10769 pins that a DHCP lease
// change racing the wipe-then-stop window does not re-render the resolver
// file the wipe cleared.
func TestReconcileDNSFromDHCPFencedDuringReset10769(t *testing.T) {
	d := &Daemon{applySem: semaphore.NewWeighted(1)}
	var calls int
	d.reconcileDNSFn = func(*config.Config, bool) error {
		calls++
		return nil
	}
	d.enterResetGeneration()
	d.reconcileDNSFromDHCP()
	if calls != 0 {
		t.Fatalf("DHCP DNS reconcile during reset must not run, got %d calls", calls)
	}
}

// TestFactoryResetRestoresIdentitySymlinkAfterFailedWipe10769 pins that a
// foreign resolver symlink replaced by the wipe is restored as the same
// link on a failed reset — not converted to regular bytes read through it.
func TestFactoryResetRestoresIdentitySymlinkAfterFailedWipe10769(t *testing.T) {
	isolateFactoryResetOwnershipPaths(t)
	isolateFactoryResetIdentityPaths(t)
	isolateHandoffFlag(t)
	target := filepath.Join(t.TempDir(), "stub-resolv.conf")
	if err := os.WriteFile(target, []byte("nameserver 127.0.0.53\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(resetResolvConfPath), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, resetResolvConfPath); err != nil {
		t.Fatal(err)
	}
	d := &Daemon{applySem: semaphore.NewWeighted(1)}
	wipeErr := errors.New("wipe failed")
	if err := d.factoryReset(context.Background(), func() error {
		if err := os.Remove(resetResolvConfPath); err != nil {
			t.Fatalf("simulate resolver replacement: %v", err)
		}
		if err := os.WriteFile(resetResolvConfPath, []byte("header-only\n"), 0o600); err != nil {
			t.Fatalf("simulate resolver replacement: %v", err)
		}
		return wipeErr
	}); !errors.Is(err, wipeErr) {
		t.Fatalf("factoryReset error = %v, want %v", err, wipeErr)
	}
	info, err := os.Lstat(resetResolvConfPath)
	if err != nil || info.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("resolver symlink was not restored as a link: info=%v err=%v", info, err)
	}
	got, err := os.Readlink(resetResolvConfPath)
	if err != nil || got != target {
		t.Fatalf("restored link target = %q, want %q (err=%v)", got, target, err)
	}
}

func TestFactoryResetRestoresKernelHostnameAfterFailedWipe10769(t *testing.T) {
	isolateFactoryResetOwnershipPaths(t)
	isolateFactoryResetIdentityPaths(t)
	isolateHandoffFlag(t)
	var renamed []string
	sethostname = func(name []byte) error {
		renamed = append(renamed, string(name))
		return nil
	}
	d := &Daemon{applySem: semaphore.NewWeighted(1)}
	wipeErr := errors.New("wipe failed")
	if err := d.factoryReset(context.Background(), func() error { return wipeErr }); !errors.Is(err, wipeErr) {
		t.Fatalf("factoryReset error = %v, want %v", err, wipeErr)
	}
	if len(renamed) != 1 || renamed[0] != "test-kernel" {
		t.Fatalf("kernel restore calls = %q, want exactly [test-kernel]", renamed)
	}
}

func TestFactoryResetSkipsKernelRestoreWhenSnapshotFails10769(t *testing.T) {
	isolateFactoryResetOwnershipPaths(t)
	isolateFactoryResetIdentityPaths(t)
	isolateHandoffFlag(t)
	osHostname = func() (string, error) { return "", errors.New("uname unavailable") }
	renamed := false
	sethostname = func([]byte) error {
		renamed = true
		return nil
	}
	d := &Daemon{applySem: semaphore.NewWeighted(1)}
	wipeErr := errors.New("wipe failed")
	// A failed kernel read must not block the reset: there is simply
	// nothing to restore the live name to.
	if err := d.factoryReset(context.Background(), func() error { return wipeErr }); !errors.Is(err, wipeErr) {
		t.Fatalf("factoryReset error = %v, want %v", err, wipeErr)
	}
	if renamed {
		t.Fatal("no kernel restore may run without a snapshot")
	}
}

// TestFactoryResetFailsWhenStateTempsReappear10769 pins the post-wipe temp
// re-verification: exact-shape fsatomic temps recreated in the
// erase→verify window must fail the reset (never silent success), be
// repaired by re-running the idempotent erasures, and converge on retry.
func TestFactoryResetFailsWhenStateTempsReappear10769(t *testing.T) {
	isolateFactoryResetOwnershipPaths(t)
	isolateFactoryResetIdentityPaths(t)
	isolateHandoffFlag(t)
	temps := []string{
		filepath.Join(filepath.Dir(resetDDNSLeaseStatePath), "."+filepath.Base(resetDDNSLeaseStatePath)+".tmp-1"),
		filepath.Join(filepath.Dir(resetIPsecStatePath), "."+filepath.Base(resetIPsecStatePath)+".tmp-1"),
	}
	d := &Daemon{applySem: semaphore.NewWeighted(1)}
	err := d.factoryReset(context.Background(), func() error {
		for _, temp := range temps {
			if err := os.MkdirAll(filepath.Dir(temp), 0o700); err != nil {
				return err
			}
			if err := os.WriteFile(temp, []byte("recreated temp"), 0o600); err != nil {
				return err
			}
		}
		return nil
	})
	if err == nil || !strings.Contains(err.Error(), "reappeared") {
		t.Fatalf("recreated temps must fail the reset, got %v", err)
	}
	for _, temp := range temps {
		if _, serr := os.Lstat(temp); !os.IsNotExist(serr) {
			t.Fatalf("reappeared temp %s must be re-erased before the failure returns: %v", temp, serr)
		}
	}
	if err := d.factoryReset(context.Background(), fakePendingWipe(t)); err != nil {
		t.Fatalf("retry after a repaired temp failure must converge: %v", err)
	}
}

// A writer that completed a full save leaves a canonical with no temp
// behind; temps-only verification would clear over it. Empty canonicals
// are repaired (removed) but still fail the reset; the retry converges.
func TestFactoryResetFailsWhenStateCanonicalsReappear10769(t *testing.T) {
	isolateFactoryResetOwnershipPaths(t)
	isolateFactoryResetIdentityPaths(t)
	isolateHandoffFlag(t)
	canonicals := map[string]string{
		resetDDNSLeaseStatePath: `{"version":1,"records":[]}`,
		resetIPsecStatePath:     `{"loaded":[],"pending_terminate":[]}`,
	}
	d := &Daemon{applySem: semaphore.NewWeighted(1)}
	err := d.factoryReset(context.Background(), func() error {
		for path, body := range canonicals {
			if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
				return err
			}
			if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
				return err
			}
		}
		return nil
	})
	if err == nil || !strings.Contains(err.Error(), "reappeared") {
		t.Fatalf("recreated canonicals must fail the reset, got %v", err)
	}
	for path := range canonicals {
		if _, serr := os.Lstat(path); !os.IsNotExist(serr) {
			t.Fatalf("reappeared canonical %s must be re-erased before the failure returns: %v", path, serr)
		}
	}
	if err := d.factoryReset(context.Background(), fakePendingWipe(t)); err != nil {
		t.Fatalf("retry after a repaired canonical failure must converge: %v", err)
	}
}

// A reappeared RECORD (not just an empty canonical) is a fence breach,
// not a repairable race: the erase refuses to delete delete-authority,
// the residue stays, and the handoff is marked dirty.
func TestFactoryResetMarksDirtyWhenStateRecordsReappear10769(t *testing.T) {
	isolateFactoryResetOwnershipPaths(t)
	isolateFactoryResetIdentityPaths(t)
	isolateHandoffFlag(t)
	withRecords := `{"version":1,"records":[{"family":4,"identity":"mac:aa","address":"203.0.113.5","fqdn":"host.example.net","forward_type":"A","ptr_name":"5.113.0.203.in-addr.arpa","ttl":300}]}`
	d := &Daemon{applySem: semaphore.NewWeighted(1)}
	err := d.factoryReset(context.Background(), func() error {
		if err := os.MkdirAll(filepath.Dir(resetDDNSLeaseStatePath), 0o700); err != nil {
			return err
		}
		return os.WriteFile(resetDDNSLeaseStatePath, []byte(withRecords), 0o600)
	})
	if err == nil || !strings.Contains(err.Error(), "reappeared") {
		t.Fatalf("recreated records must fail the reset, got %v", err)
	}
	if _, serr := os.Lstat(resetDDNSLeaseStatePath); serr != nil {
		t.Fatalf("record-bearing canonical must be preserved for operator withdrawal, stat err=%v", serr)
	}
	_, dirty, _, present, rerr := configstore.ReadResetHandoff()
	if rerr != nil || !present || !strings.HasPrefix(dirty, configstore.ResetHandoffReasonTemps+":") {
		t.Fatalf("record reappearance must mark temps-dirty: dirty=%q present=%v err=%v", dirty, present, rerr)
	}
	if err := configstore.CheckResetHandoff(); !errors.Is(err, configstore.ErrResetHandoffDirty) {
		t.Fatalf("gate over record residue = %v, want incomplete", err)
	}
}
