// #9726: build.rs uses these functions to decide whether a helper builds and
// what it records, so each decision is pinned on both sides of its boundary.
use crate::build_libversions::{
    check_libbpf_family, check_libxdp_version, header_define, locked_package_version,
};

#[test]
fn check_libxdp_version_admits_only_the_validated_range_9726() {
    for version in ["1.6.3", "1.6.9"] {
        assert_eq!(check_libxdp_version(version), Ok(()), "libxdp {version}");
    }
    for version in ["1.6.2", "1.7.0"] {
        let err = check_libxdp_version(version).expect_err(version);
        assert!(
            err.contains(&format!(
                "libxdp {version} is outside the validated range >= 1.6.3, < 1.7"
            )),
            "{err}"
        );
    }
    // A version without a patch reads as 1.6.0, below the range, not unparsable.
    let err = check_libxdp_version("1.6").expect_err("1.6");
    assert!(
        err.contains("libxdp 1.6 is outside the validated range"),
        "{err}"
    );
    let err = check_libxdp_version("1.x").expect_err("1.x");
    assert!(err.contains("unparsable libxdp version \"1.x\""), "{err}");
}

#[test]
fn check_libbpf_family_requires_1_6_in_the_headers_and_the_lock_9726() {
    assert_eq!(
        check_libbpf_family(1, 6, "1.6.3+v1.6.3"),
        Ok("1.6.3".to_string())
    );
    // The libbpf version is the part after "+v", not the crate version before it.
    assert_eq!(
        check_libbpf_family(1, 6, "1.6.0+v1.6.3"),
        Ok("1.6.3".to_string())
    );
    // Without "+v", the crate version is the libbpf version.
    assert_eq!(check_libbpf_family(1, 6, "1.6.1"), Ok("1.6.1".to_string()));

    // Headers and lock agree, but on a family nothing validated.
    let err = check_libbpf_family(1, 7, "1.7.0+v1.7.0").expect_err("headers 1.7");
    assert!(
        err.contains("vendored libbpf headers are 1.7, outside the validated family 1.6"),
        "{err}"
    );
    // Headers in the family, but the lock pins another one.
    let err = check_libbpf_family(1, 6, "1.7.0+v1.7.0").expect_err("lock 1.7");
    assert!(
        err.contains(
            "Cargo.lock pins libbpf-sys 1.7.0+v1.7.0, but its vendored libbpf headers are 1.6"
        ),
        "{err}"
    );
    let err = check_libbpf_family(1, 6, "1.x").expect_err("unparsable lock");
    assert!(err.contains("unparsable libbpf version"), "{err}");
}

#[test]
fn locked_package_version_reads_only_the_named_package_9726() {
    let lock = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "libbpf-sys"
version = "1.6.3+v1.6.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "cc",
 "nix",
]

[[package]]
name = "libc"
version = "0.2.180"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#;
    assert_eq!(
        locked_package_version(lock, "libbpf-sys").as_deref(),
        Some("1.6.3+v1.6.3")
    );
    assert_eq!(
        locked_package_version(lock, "libc").as_deref(),
        Some("0.2.180")
    );
    // Named only in a dependencies list, and not named at all.
    assert_eq!(locked_package_version(lock, "cc"), None);
    assert_eq!(locked_package_version(lock, "libbpf-rs"), None);
}

#[test]
fn header_define_reads_only_a_numeric_define_9726() {
    let header = "\
/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */
#ifndef __LIBBPF_VERSION_H
#define __LIBBPF_VERSION_H

#define LIBBPF_MAJOR_VERSION 1
#define LIBBPF_MINOR_VERSION 6

#endif /* __LIBBPF_VERSION_H */
";
    assert_eq!(header_define(header, "LIBBPF_MAJOR_VERSION"), Some(1));
    assert_eq!(header_define(header, "LIBBPF_MINOR_VERSION"), Some(6));
    // Defined without a value, and not defined.
    assert_eq!(header_define(header, "__LIBBPF_VERSION_H"), None);
    assert_eq!(header_define(header, "LIBBPF_PATCH_VERSION"), None);
}

// #9726: what this build recorded passes the checks, and the recorded libbpf is
// the full version Cargo.lock pins rather than the headers' major.minor.
#[test]
fn recorded_library_versions_pass_the_build_checks_9726() {
    let libxdp = env!("XPF_LINKED_LIBXDP_VERSION");
    assert_eq!(
        check_libxdp_version(libxdp),
        Ok(()),
        "recorded libxdp {libxdp}"
    );

    let lock = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.lock"));
    let locked = locked_package_version(lock, "libbpf-sys").expect("Cargo.lock locks libbpf-sys");
    let expected = locked
        .split_once("+v")
        .map_or(locked.as_str(), |(_, libbpf)| libbpf);
    assert_eq!(
        env!("XPF_LINKED_LIBBPF_VERSION"),
        expected,
        "Cargo.lock locks libbpf-sys {locked}"
    );
}
