#!/usr/bin/env python3
"""#12141/#12158: package and bake identities cover the complete build input."""

from __future__ import annotations

import importlib.util
import os
import subprocess
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest import mock

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parent.parent
_SPEC = importlib.util.spec_from_file_location("xpf_bake_provenance", _HERE / "bake.py")
bake = importlib.util.module_from_spec(_SPEC)
assert _SPEC.loader is not None
_SPEC.loader.exec_module(bake)


class BuildProvenanceTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory(prefix="xpf-provenance-12141-")
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name)
        (self.root / "pkg").mkdir()
        (self.root / "scripts/image").mkdir(parents=True)
        (self.root / "docs").mkdir()
        (self.root / "debian").mkdir()
        (self.root / ".gitignore").write_bytes(
            (_REPO / ".gitignore").read_bytes() + b"\n/pkg/generated/\n")
        (self.root / "debian/.gitignore").write_bytes(
            (_REPO / "debian/.gitignore").read_bytes())
        (self.root / "pkg/app.go").write_text("package pkg\nvar Value = 1\n")
        (self.root / "scripts/image/build_provenance.py").write_bytes(
            (_HERE / "build_provenance.py").read_bytes())
        makefile = (_REPO / "Makefile").read_text(encoding="utf-8")
        makefile += (
            "\n.PHONY: provenance-test-dirty\n"
            "provenance-test-dirty:\n"
            "\t@printf '%s' '$(DEB_GIT_DIRTY)'\n"
        )
        (self.root / "Makefile").write_text(makefile)
        self.git("init", "-q")
        self.git("config", "user.name", "Provenance Test")
        self.git("config", "user.email", "provenance@example.invalid")
        self.git("add", ".")
        self.git("commit", "-qm", "fixture base")

    def git(self, *args, check=True):
        return subprocess.run(
            ["git", "-C", str(self.root), *args], check=check,
            capture_output=True, text=True)

    def make_suffix(self):
        return subprocess.check_output(
            ["make", "-s", "--no-print-directory", "-C", str(self.root),
             "provenance-test-dirty"], text=True)

    def assert_dirty_parity(self, dirty):
        expected = f"0.0.1+g{self.git('rev-parse', '--short=12', 'HEAD').stdout.strip()}"
        if dirty:
            expected += ".dirty"
        self.assertEqual(bake.deb_version_for_head(str(self.root)), expected)
        self.assertEqual(self.make_suffix(), ".dirty" if dirty else "")

    def test_clean_source_is_clean_in_bake_and_make(self):
        self.assert_dirty_parity(False)

    def test_deb_generated_unit_copies_do_not_dirty_clean_source(self):
        for name in (
                "xpf.xpf-uefi-slots.service",
                "xpf.xpf-kernel-promote.service",
                "xpf.xpf-kernel-promote-failed.service"):
            (self.root / "debian" / name).write_text("# generated by debhelper\n")
        self.assert_dirty_parity(False)

    def test_staged_tracked_edit_is_dirty_in_bake_and_make(self):
        with (self.root / "pkg/app.go").open("a") as source:
            source.write("var Staged = 2\n")
        self.git("add", "pkg/app.go")
        self.assertEqual(self.git("diff", "--quiet", check=False).returncode, 0)
        self.assert_dirty_parity(True)

    def test_consumed_untracked_go_source_is_dirty_in_bake_and_make(self):
        (self.root / "pkg/new.go").write_text("package pkg\nvar New = 3\n")
        self.assertEqual(self.git("diff", "--quiet", check=False).returncode, 0)
        self.assert_dirty_parity(True)

    def test_ignored_but_compiled_bpf_go_source_is_dirty(self):
        dataplane = self.root / "pkg/dataplane"
        dataplane.mkdir()
        source = dataplane / "zz_bpfel.go"
        source.write_text("package dataplane\nvar ignoredBuildInput = 1\n")
        self.git("check-ignore", "pkg/dataplane/zz_bpfel.go")
        self.assert_dirty_parity(True)

    def test_unstaged_tracked_edit_is_dirty_in_bake_and_make(self):
        with (self.root / "pkg/app.go").open("a") as source:
            source.write("var Unstaged = 4\n")
        self.assert_dirty_parity(True)

    def test_unrelated_or_ignored_untracked_files_do_not_dirty_build(self):
        (self.root / "docs/unconsumed.txt").write_text("notes\n")
        (self.root / "pkg/generated").mkdir()
        (self.root / "pkg/generated/ignored.go").write_text("package pkg\n")
        deploy_tools = self.root / "scripts/deploy"
        deploy_tools.mkdir()
        (deploy_tools / "unconsumed.py").write_text("# not used by package/bake\n")
        self.assert_dirty_parity(False)

    def test_make_rejects_dirty_source_when_suffix_override_hides_it(self):
        with (self.root / "pkg/app.go").open("a") as source:
            source.write("var Dirty = 5\n")
        clean_version = (
            "0.0.1+g" + self.git("rev-parse", "--short=12", "HEAD").stdout.strip())
        result = subprocess.run(
            ["make", "-s", "--no-print-directory", "-C", str(self.root),
             "deb", "DEB_GIT_DIRTY=", f"DEB_VERSION={clean_version}"],
            capture_output=True, text=True, check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "FATAL: DEB_VERSION dirty suffix disagrees with source inputs",
            result.stderr)

    def test_explicit_clean_version_cannot_name_dirty_source(self):
        clean_version = bake.deb_version_for_head(str(self.root))
        (self.root / "pkg/new.go").write_text("package pkg\nvar New = 3\n")
        dirty_version = bake.deb_version_for_head(str(self.root))
        with self.assertRaises(SystemExit) as caught:
            bake.require_current_build_version(clean_version, dirty_version)
        self.assertIn("does not match current build provenance", str(caught.exception))

    def test_main_rejects_explicit_clean_version_before_building_dirty_source(self):
        args = SimpleNamespace(
            version="0.0.1+gabcdef012345", skip_build=False)
        with (
            mock.patch.object(
                bake.argparse.ArgumentParser, "parse_args", return_value=args),
            mock.patch.object(
                bake, "deb_version_for_head",
                return_value="0.0.1+gabcdef012345.dirty"),
            mock.patch.dict(os.environ, {}, clear=True),
        ):
            with self.assertRaises(SystemExit) as caught:
                bake.main()
        self.assertIn("does not match current build provenance",
                      str(caught.exception))


if __name__ == "__main__":
    unittest.main()
