// CoS classification: maps a packet's policy/filter/classifier
// signals to a CoS queue id and an optional DSCP rewrite, then
// enqueues onto the chosen queue. Single-writer (owner worker);
// atomic ops use `Ordering::Relaxed`.

use super::*;
use crate::afxdp::mirror::MIRROR_TX_FRAME_RESERVE;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(in crate::afxdp) struct CoSTxSelection {
    pub(in crate::afxdp) queue_id: Option<u8>,
    pub(in crate::afxdp) dscp_rewrite: Option<u8>,
    pub(in crate::afxdp) drop: bool,
    // #3608: `drop` folds every non-`Accept` output-filter action plus any
    // three-color-policer drop into one bit. `reject` isolates the subset that
    // was an explicit output-filter `then reject` (`FilterAction::Reject(RejectMessage::ADMIN_PROHIBITED)`), so
    // the TX/CoS consumer can synthesize the active reject reply (TCP RST /
    // ICMP admin-prohibited) instead of the silent drop a `then discard` or a
    // red policer produces. `reject` is only ever true when `drop` is true; a
    // policer drop or a `then discard` keeps `reject == false`.
    pub(in crate::afxdp) reject: bool,
    // #6854: the ICMP codes the matched term's `then reject <message-type>`
    // resolved to. Meaningless unless `reject` is true, and defaults to
    // administratively-prohibited, which is what every reject on this path
    // sent before #6854 — so an output filter whose term carries no
    // message-type is bit-identical to the old behaviour.
    pub(in crate::afxdp) reject_message: crate::filter::RejectMessage,
    pub(in crate::afxdp) filter_log: Option<crate::filter::FilterLogMatch>,
}

fn map_cached_forwarding_class_queue(
    iface: &CoSInterfaceConfig,
    forwarding_class: Option<&Arc<str>>,
) -> Option<u8> {
    forwarding_class.and_then(|class| iface.queue_by_forwarding_class.get(class.as_ref()).copied())
}

/// #2238: classification verdict for a LOCALLY-GENERATED reply frame,
/// derived from the reply's OWN egress 5-tuple + egress interface (not the
/// triggering inbound packet's tuple). `drop == true` means an output
/// firewall filter terminal `discard`/`reject` (or a three-color policer)
/// on the egress interface dropped the reply, OR the generated bytes could
/// not be parsed (fail-CLOSED, §6.2). On `parse_error == true` the caller
/// MUST attribute the drop on a dedicated parse-error counter (a parse
/// failure of our own bytes is a logic bug, never silent).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(in crate::afxdp) struct GeneratedReplyVerdict {
    pub(in crate::afxdp) drop: bool,
    pub(in crate::afxdp) parse_error: bool,
    pub(in crate::afxdp) cos_queue_id: Option<u8>,
    pub(in crate::afxdp) dscp_rewrite: Option<u8>,
    pub(in crate::afxdp) filter_log: Option<crate::filter::FilterLogMatch>,
}

/// #2238: classify a host-generated reply frame by its OWN egress tuple.
///
/// Parses the BUILT reply bytes (`frame`) into the generated frame's
/// `(SessionKey, ForwardPacketMeta)` and runs the runtime-counted output
/// classifier ([`resolve_cos_tx_selection_at`]) on that tuple + the egress
/// interface. This is the single contract every generator (ICMP/ICMPv6 Time
/// Exceeded, policy-`reject` RST/ICMP-unreachable, SYN-cookie SYN-ACK/
/// ACK-RST) routes through so output-filter counters/log/policers are
/// charged exactly once, identically to transit, but keyed on the REPLY's
/// real tuple rather than the trigger's.
///
/// Fail-CLOSED on a parse failure (#2238 §6.2): an output-filter terminal
/// `discard`/`reject` is a security boundary, so a reply whose own bytes
/// cannot be re-parsed is DROPPED (`drop: true, parse_error: true`) rather
/// than leaked past the filter. The bytes are our own, so this only fires on
/// a builder/parser logic bug — the caller's dedicated parse-error counter
/// keeps the event attributable.
///
/// Cold path only — every caller is on a generator's exception arm. The
/// added work is one L2/L3/L4 walk + one filter eval, never per transit
/// packet.
pub(in crate::afxdp) fn classify_generated_reply(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    frame: &[u8],
    now_ns: u64,
) -> GeneratedReplyVerdict {
    let Some((key, meta)) = generated_reply_session_key(frame) else {
        // §6.2: cannot classify our own generated bytes — fail CLOSED.
        return GeneratedReplyVerdict {
            drop: true,
            parse_error: true,
            cos_queue_id: None,
            dscp_rewrite: None,
            filter_log: None,
        };
    };
    // #2362 fold B: classify the generated reply on its OWN bytes — build the
    // fragment-safe per-packet match inputs from the reply frame so a
    // tcp-flags / icmp-type output-filter term matches the reply correctly.
    // #6435: the single unified builder (the byte-identical
    // `term_match_extra_from_frame_fwd` twin is retired; the builder now
    // takes `impl Into<ForwardPacketMeta>`).
    let extra = crate::afxdp::frame::term_match_extra_from_frame(frame, meta);
    let selection =
        resolve_cos_tx_selection_at(forwarding, egress_ifindex, meta, Some(&key), extra, now_ns);
    GeneratedReplyVerdict {
        drop: selection.drop,
        parse_error: false,
        cos_queue_id: selection.queue_id,
        dscp_rewrite: selection.dscp_rewrite,
        filter_log: selection.filter_log,
    }
}

/// #8367: which tuple a cached TX-selection descriptor is resolved from.
///
/// Both variants carry a REQUIRED post-NAT on-wire key, and that requirement is
/// the point of the type. An interface `filter output` is applied on the EGRESS
/// interface AFTER NAT (#3642), so there is no correct descriptor to build
/// without one — yet before #8367 the flowless arm took `flow_key: None` and
/// silently substituted the ingress (PRE-NAT) `meta` for three separate reads:
/// the filter FAMILY, the matched ADDRESSES and the PROTOCOL. Under plain
/// SNAT/DNAT that made the verdict *confidently wrong* rather than merely
/// absent — it populated `.drop`, `.reject`, `.reject_message`, `.filter_log`
/// and the counter/policer handles from a tuple the packet no longer carries,
/// so a `from source-address <pool>` term did not match a packet whose on-wire
/// source IS the pool address, and a `then log` recorded the pre-translation
/// addresses for a packet that left with different ones.
///
/// Encoding the key as a required field of the variant, rather than an `Option`
/// the caller may omit, is the fix: a caller that wants a filter verdict must
/// supply the tuple the packet leaves with, and cannot get a wrong one by
/// default. A caller that wants only the CoS queue asks for the queue — see
/// [`resolve_cached_cos_tx_queue_id`], which is what the port-mirror path
/// (`mirror::mirror_cos_queue_id`, the only production caller that ever reached
/// the flowless arm) now uses.
pub(in crate::afxdp) enum CachedTxTuple<'a> {
    /// A flow-bearing packet. `egress_wire_key` is the POST-NAT on-wire tuple
    /// (#3642) driving the egress OUTPUT filter family + match and the CoS
    /// queue; `ingress_flow_key` is the PRE-NAT ingress tuple the INPUT filter
    /// originally matched (#5158, Junos applies input filters BEFORE NAT). They
    /// are the same key for a non-NAT flow.
    Flow {
        egress_wire_key: &'a SessionKey,
        ingress_flow_key: &'a SessionKey,
    },
    /// A FLOWLESS packet — a non-first IP fragment or a non-query ICMP
    /// error/control packet, both of which carry no usable L4 ports
    /// (#2344/#3290). `wire_l3` is the POST-NAT L3-only on-wire tuple, built the
    /// way the flow-bearing path builds its wire key
    /// (`forward_request::l3_wire_session_flow_from_meta` -> `forward_wire_key`),
    /// so family, addresses and protocol move together BY CONSTRUCTION rather
    /// than as three reads that can drift apart. Its ports are never read: this
    /// arm evaluates through the PORTLESS evaluator (#7992).
    Flowless { wire_l3: &'a SessionKey },
}

pub(in crate::afxdp) fn resolve_cached_cos_tx_selection(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: UserspaceDpMeta,
    flow_key: &SessionKey,
) -> CachedTxSelectionDescriptor {
    // Non-NAT / single-key callers: the ingress input-filter re-walk uses the
    // same tuple as the output filter (there is no post-NAT/pre-NAT split).
    resolve_cached_cos_tx_selection_impl(
        forwarding,
        egress_ifindex,
        meta,
        CachedTxTuple::Flow {
            egress_wire_key: flow_key,
            ingress_flow_key: flow_key,
        },
    )
}

/// #8367: cached TX-selection for a FLOWLESS packet. `wire_l3` is REQUIRED and
/// must be the POST-NAT on-wire L3 tuple — the same value the flow-bearing seed
/// path derives with `forward_wire_key(&flow.forward_key, decision.nat)` and the
/// fresh flowless arm derives with `l3_wire_session_flow_from_meta` (#7656).
/// Passing the raw ingress `meta` tuple here for a NAT'd packet reintroduces the
/// #8367 defect; there is deliberately no entry point that lets the key be
/// omitted, because "no tuple" and "the pre-NAT tuple" are not the same answer
/// and only one of them is honest.
pub(in crate::afxdp) fn resolve_cached_cos_tx_selection_flowless(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: UserspaceDpMeta,
    wire_l3: &SessionKey,
) -> CachedTxSelectionDescriptor {
    resolve_cached_cos_tx_selection_impl(
        forwarding,
        egress_ifindex,
        meta,
        CachedTxTuple::Flowless { wire_l3 },
    )
}

/// #8367: the CoS queue id alone, for a caller that consumes a queue and
/// nothing else — today the port-mirror / span path
/// (`mirror::mirror_cos_queue_id`).
///
/// For a flow-bearing packet this is the full descriptor's `queue_id`, byte for
/// byte what the mirror path resolved before. For a FLOWLESS one it is the
/// behavior-aggregate lookup alone (DSCP -> inet-precedence -> 802.1p -> the
/// interface default queue), which is 5-tuple independent (#hb166 T-6(m)) and
/// was already computed BEFORE and INDEPENDENTLY of the output-filter block
/// whose verdict this caller discards — so the value is unchanged and the
/// mirror path no longer asks for fields it throws away.
///
/// That split is what lets the flowless descriptor arm REQUIRE a post-NAT wire
/// key. The mirror caller has no `NatDecision` to synthesize one from, and
/// threading a decision through the mirror path to populate fields the mirror
/// path discards would be a poor trade; asking for what it actually consumes
/// costs nothing and removes the last caller that could reach a filter verdict
/// with no tuple to compute it from.
pub(in crate::afxdp) fn resolve_cached_cos_tx_queue_id(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: UserspaceDpMeta,
    flow_key: Option<&SessionKey>,
) -> Option<u8> {
    match flow_key {
        Some(flow_key) => {
            resolve_cached_cos_tx_selection(forwarding, egress_ifindex, meta, flow_key).queue_id
        }
        None => forwarding
            .cos
            .interfaces
            .get(&egress_ifindex)
            .map(|iface| flowless_cos_ba_queue_id(iface, meta)),
    }
}

/// The behavior-aggregate (BA) queue for a FLOWLESS packet: DSCP classifier ->
/// inet-precedence classifier -> 802.1p classifier -> the interface default
/// queue (#hb166 T-6(m) / #6847). 5-tuple independent by construction, which is
/// why it is the one part of a flowless CoS resolution that needs no post-NAT
/// wire key (#8367) — an EF fragment lands in its BA queue whether or not the
/// caller can supply a tuple.
///
/// Shared by the two sites #8367 needed to keep in agreement: the cached
/// flowless descriptor arm and the mirror queue-only entry point, which MUST
/// return the same queue or the split would be a behaviour change wearing the
/// shape of a refactor. It is NOT the file's only spelling of the chain —
/// `resolve_cos_tx_selection_internal`'s flowless arm takes a
/// `ForwardPacketMeta` rather than a `UserspaceDpMeta`, and
/// `reclassify_cached_ba_queue` ends the chain with `.or(Some(default))`
/// instead of `.unwrap_or(default)` because its caller needs the `Option`.
/// Folding those in is a separate change with its own risk.
fn flowless_cos_ba_queue_id(iface: &CoSInterfaceConfig, meta: UserspaceDpMeta) -> u8 {
    resolve_cos_dscp_classifier_queue_id(iface, meta.dscp)
        .or_else(|| resolve_cos_inet_precedence_classifier_queue_id(iface, meta.dscp))
        .or_else(|| {
            resolve_cos_ieee8021_classifier_queue_id(
                iface,
                meta.ingress_pcp,
                meta.ingress_vlan_present != 0,
            )
        })
        .unwrap_or(iface.default_queue)
}

/// #5158: cached-seed TX-selection variant for the POST-NAT transit forward
/// path. `egress_wire_key` (the post-NAT on-wire tuple, #3642) drives the
/// egress OUTPUT filter + CoS queue selection; `ingress_flow_key` (the PRE-NAT
/// ingress tuple the input filter originally matched) drives the ingress INPUT
/// filter re-walk. The flow-cache seed (`flow_cache.rs`) builds the post-NAT
/// wire key with `forward_wire_key` and passes the pre-NAT session
/// `forward_key` as `ingress_flow_key`, so NAT'd traffic still picks up an
/// ingress `then forwarding-class` / dscp-rewrite / three-color policer.
pub(in crate::afxdp) fn resolve_cached_cos_tx_selection_prenat(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: UserspaceDpMeta,
    egress_wire_key: &SessionKey,
    ingress_flow_key: &SessionKey,
) -> CachedTxSelectionDescriptor {
    resolve_cached_cos_tx_selection_impl(
        forwarding,
        egress_ifindex,
        meta,
        CachedTxTuple::Flow {
            egress_wire_key,
            ingress_flow_key,
        },
    )
}

/// #8367: the FLOWLESS arm of the cached TX-selection descriptor, split out of
/// `resolve_cached_cos_tx_selection_impl` so its post-NAT wire key is a required
/// parameter rather than an omitted `Option`.
///
/// `wire_l3` is the POST-NAT on-wire L3 tuple. Every read that used to fall back
/// to the ingress `meta` — the output-filter FAMILY, the matched ADDRESSES and
/// the PROTOCOL — now comes from it, as ONE choice rather than three. That is
/// the property #7656 established on the fresh (`resolve_cos_tx_selection_at`)
/// flowless arm and #8367 brings here: a mixture — egress family with ingress
/// addresses — selects the right filter and then cannot match any
/// address-bearing term in it, which no address-less fixture can see.
fn cached_cos_tx_selection_flowless(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: UserspaceDpMeta,
    wire_l3: &SessionKey,
) -> CachedTxSelectionDescriptor {
    let iface = forwarding.cos.interfaces.get(&egress_ifindex);
    // #hb166 T-6(m): fragments / flowless packets carry no 5-tuple but
    // still carry a DSCP (and 802.1p PCP). Behavior-aggregate
    // classification is 5-tuple-independent — resolve it from `meta` so
    // an EF fragment lands in its BA queue instead of straddling the
    // default queue. Filter forwarding-class / rewrite needs the flow
    // key, so those stay unset (as before).
    let queue_id = iface.map(|iface| flowless_cos_ba_queue_id(iface, meta));
    // #3995: flowless packets still resolve the loss-priority-aware CoS
    // rewrite from their own DSCP/PCP (default LOW when unclassified).
    let dscp_rewrite = queue_id.and_then(|queue_id| {
        resolve_cos_queue_lp_rewrite(
            forwarding,
            egress_ifindex,
            queue_id,
            meta.dscp,
            meta.ingress_pcp,
            meta.ingress_vlan_present != 0,
        )
    });
    // #6055: bring this cached flowless arm to PARITY with the #5467 fix on
    // `resolve_cos_tx_selection_internal`'s flowless arm. Before this gate the
    // cached flowless arm returned `drop:false, reject:false, filter_log:None`
    // WITHOUT ever evaluating the interface `filter output` — a LATENT
    // fail-open: any caller that reads `.drop`/`.reject` from a flowless
    // result (a future seed/mirror refactor) would silently wave a
    // would-be-dropped flowless packet (a non-first IP fragment / non-query
    // ICMP error/control packet, #2344/#3290) past an egress `then discard`/
    // `reject` term. Evaluate the output filter against the packet's own
    // POST-NAT L3 tuple (src/dst/protocol from `wire_l3`; L4 ports absent) and
    // honor the drop/reject/log verdict exactly as the flow-keyed arm below
    // does, so an L3-matching deny FAILS CLOSED.
    //
    // Uses the cache-replay eval the flow-keyed arm uses — it captures
    // `then count`/policer handles into the descriptor and applies
    // `TermMatchExtra::default()`, which fails every per-packet-L4 term
    // (tcp-flags/icmp-type/icmp-code/is-fragment/flex) closed. The flow-cache
    // SEED path already DECLINES caching for a filter carrying such a term
    // (`interface_output_filter_has_per_packet_l4_match`, flow_cache.rs), so no
    // per-packet-L4 output term reaches this arm; only an L3-only
    // (`from source-address`/`destination-address`/`protocol`/bare `then`) term
    // takes effect, matching the #5467 flowless contract. The `drop` bit is the
    // OUTPUT filter's terminal action only (a three-color policer runs at
    // replay via `apply_cached_three_color_policers`), identical to the
    // flow-keyed arm's #3608 convention.
    //
    // #8367: family, addresses and protocol are read as ONE choice from
    // `wire_l3`. They used to be three independent reads of the ingress `meta`,
    // which is the PRE-NAT tuple for any translated packet: `from
    // source-address <pool>` did not match a packet whose on-wire source IS the
    // pool address, and `from source-address <private range>` matched one that
    // no longer carries it. Junos applies an interface `filter output` on the
    // egress interface AFTER NAT (#3642).
    let is_v6 = wire_l3.addr_family as i32 == libc::AF_INET6;
    let mut drop = false;
    let mut reject = false;
    // #6854: meaningless unless `reject`; see CoSTxSelection.reject_message.
    let mut reject_message = crate::filter::RejectMessage::ADMIN_PROHIBITED;
    let mut filter_log = None;
    let mut filter_counters = crate::filter::CachedFilterCounters::default();
    let mut three_color_policers = crate::filter::CachedThreeColorPolicers::default();
    // #6236 PR-2C: fold the `needs_tx_eval` precheck and the output-filter
    // fetch into ONE lookup — `interface_output_filter_needing_tx_eval`
    // borrows the filter gated on `Filter::needs_tx_eval()`, replacing the
    // separate bool accessor + `.get()` + re-`filter(needs_tx_eval)`.
    if let Some(output_filter) = crate::filter::interface_output_filter_needing_tx_eval(
        &forwarding.filter_state,
        egress_ifindex,
        is_v6,
    ) {
        // #7992: the PORTLESS evaluator. This arm has no flow, so it has no
        // ports — and literal `0, 0` is not "no port", it is a port value a
        // term can match on. `destination-port-except 22` matches everything
        // that is not 22, and 0 is not 22, so the exception matched and an
        // egress `then discard` fired on a packet whose real port was
        // excepted. Port-bearing terms now DECLINE here in both directions,
        // which matches this arm's stated contract that only L3-only terms
        // take effect.
        let output_result = crate::filter::evaluate_filter_ref_tx_selection_cached_portless(
            output_filter,
            wire_l3.src_ip,
            wire_l3.dst_ip,
            wire_l3.protocol,
            meta.dscp,
        );
        drop = output_result.action != crate::filter::FilterAction::Accept;
        reject = matches!(output_result.action, crate::filter::FilterAction::Reject(_));
        reject_message = if let crate::filter::FilterAction::Reject(m) = output_result.action {
            m
        } else {
            crate::filter::RejectMessage::ADMIN_PROHIBITED
        };
        filter_log = output_result.log_match;
        filter_counters = output_result.counters;
        three_color_policers = output_result.three_color_policers;
    }
    CachedTxSelectionDescriptor {
        queue_id,
        dscp_rewrite,
        drop,
        reject,
        reject_message,
        filter_counters,
        three_color_policers,
        filter_log,
        // Flowless packets are re-resolved per packet (no cache entry),
        // so there is nothing to mark for hit-path re-classification.
        ba_reclassify: false,
    }
}

fn resolve_cached_cos_tx_selection_impl(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: UserspaceDpMeta,
    tuple: CachedTxTuple<'_>,
) -> CachedTxSelectionDescriptor {
    // #8367: exhaustive, no `_` arm. A third tuple shape (a future caller with a
    // different post-NAT provenance) must be made to state which arm it takes
    // rather than falling into whichever one happens to be the wildcard.
    let (flow_key, ingress_flow_key) = match tuple {
        CachedTxTuple::Flowless { wire_l3 } => {
            return cached_cos_tx_selection_flowless(forwarding, egress_ifindex, meta, wire_l3);
        }
        CachedTxTuple::Flow {
            egress_wire_key,
            ingress_flow_key,
        } => (egress_wire_key, ingress_flow_key),
    };
    let iface = forwarding.cos.interfaces.get(&egress_ifindex);

    // #3642: select the output-filter family from the (post-NAT) wire key the
    // caller passes, not `meta.addr_family`. For a NAT64 flow the egress family
    // differs from the ingress meta family; `flow_key` is already unwrapped to
    // the egress wire key here, so its `addr_family` is the correct egress one.
    let is_v6 = flow_key.addr_family as i32 == libc::AF_INET6;
    // #5158: the ingress INPUT filter matched the packet on its PRE-NAT ingress
    // tuple (Junos applies input filters BEFORE NAT), so its re-walk below runs
    // on the pre-NAT `ingress_flow_key` and the ingress-side family, NOT the
    // post-NAT egress wire key `flow_key`/`is_v6` (#3642, correct only for the
    // OUTPUT filter). For a non-NAT flow both keys — and both families — match.
    let ingress_is_v6 = ingress_flow_key.addr_family as i32 == libc::AF_INET6;
    // #6236 PR-2C: one lookup for both the gate and the walk. The borrow is gated
    // on `Filter::needs_tx_eval()`, so `has_output_tx_eval` is just `.is_some()`
    // and `output_filter` needs no second `.get()` or re-`filter(needs_tx_eval)`.
    // The PR-2A `has_output_needs_tx_eval_*` aggregate already short-circuited the
    // whole path upstream (`tx_selection_enabled`), so this per-interface lookup
    // only runs when a needs-tx-eval filter exists SOMEWHERE.
    let output_filter = crate::filter::interface_output_filter_needing_tx_eval(
        &forwarding.filter_state,
        egress_ifindex,
        is_v6,
    );
    let has_output_tx_eval = output_filter.is_some();
    let has_input_tx_selection =
        crate::filter::filter_state_has_input_tx_selection(&forwarding.filter_state, ingress_is_v6);
    let has_input_three_color_policer =
        crate::filter::filter_state_has_input_three_color_policer(
            &forwarding.filter_state,
            ingress_is_v6,
        );
    if iface.is_none()
        && !has_output_tx_eval
        && !has_input_tx_selection
        && !has_input_three_color_policer
    {
        return CachedTxSelectionDescriptor::default();
    }
    let output_result = output_filter
        .map(|filter| {
            crate::filter::evaluate_filter_ref_tx_selection_cached(
                filter,
                flow_key.src_ip,
                flow_key.dst_ip,
                flow_key.protocol,
                flow_key.src_port,
                flow_key.dst_port,
                meta.dscp,
            )
        })
        .unwrap_or_default();

    let mut effective_dscp_rewrite = output_result.dscp_rewrite;
    let mut forwarding_class = output_result.forwarding_class.clone();
    let mut filter_counters = output_result.counters;
    let mut three_color_policers = output_result.three_color_policers;
    let filter_log = output_result.log_match;

    // #hb166 T-3 (cached mirror): evaluate the ingress input filter for its
    // forwarding-class whenever an input tx-selection filter (or policer)
    // exists, INCLUDING when an output filter is attached. `forwarding_class`
    // is folded with `.or()` so a `then forwarding-class` on the output filter
    // still wins and the input class only fills the gap — output-overrides-
    // when-set, not presence-clears-ingress. The cached counter set stays the
    // output filter's when an output filter is present (the ingress input
    // filter's counters are captured separately on the cached hit path via
    // `evaluate_interface_input_filter_counters_cached`, #3777/#4085), so the
    // `if output_filter.is_none()` gate on `filter_counters` is preserved.
    if has_input_tx_selection || has_input_three_color_policer {
        let ingress_ifindex = resolve_ingress_logical_ifindex(
            forwarding,
            meta.ingress_ifindex as i32,
            meta.ingress_vlan_id,
        )
        .unwrap_or(meta.ingress_ifindex as i32);
        let ingress_filter = if ingress_is_v6 {
            forwarding
                .filter_state
                .iface_filter_v6_fast
                .get(&ingress_ifindex)
                .map(Arc::as_ref)
        } else {
            forwarding
                .filter_state
                .iface_filter_v4_fast
                .get(&ingress_ifindex)
                .map(Arc::as_ref)
        };
        if let Some(ingress_filter) = ingress_filter.filter(|filter| {
            filter.affects_tx_selection || filter.has_three_color_policer_terms
        }) {
            // #5158: re-walk on the PRE-NAT ingress tuple, not `flow_key` (the
            // post-NAT egress wire key the output filter used above).
            let ingress_result = crate::filter::evaluate_filter_ref_tx_selection_cached(
                ingress_filter,
                ingress_flow_key.src_ip,
                ingress_flow_key.dst_ip,
                ingress_flow_key.protocol,
                ingress_flow_key.src_port,
                ingress_flow_key.dst_port,
                meta.dscp,
            );
            effective_dscp_rewrite = effective_dscp_rewrite.or(ingress_result.dscp_rewrite);
            forwarding_class = forwarding_class.or(ingress_result.forwarding_class);
            if output_filter.is_none() {
                filter_counters = ingress_result.counters;
            }
            three_color_policers.extend(ingress_result.three_color_policers);
        }
    }

    // #3778: split the forwarding-class queue (5-tuple-stable) from the BA
    // classifier queue (per-packet). A filter `then forwarding-class` pins the
    // queue for the flow's lifetime and stays cached; a DSCP / 802.1p BA
    // classifier picks the queue from THIS packet's DSCP / PCP and must be
    // re-resolved on every hit.
    let fc_queue =
        iface.and_then(|iface| map_cached_forwarding_class_queue(iface, forwarding_class.as_ref()));
    let queue_id = fc_queue.or_else(|| {
        iface.and_then(|iface| {
            resolve_cos_dscp_classifier_queue_id(iface, meta.dscp)
                .or_else(|| resolve_cos_inet_precedence_classifier_queue_id(iface, meta.dscp))
                .or_else(|| {
                    resolve_cos_ieee8021_classifier_queue_id(
                        iface,
                        meta.ingress_pcp,
                        meta.ingress_vlan_present != 0,
                    )
                })
                .or(Some(iface.default_queue))
        })
    });
    // Mark for per-packet BA re-classification on the flow-cache hit path only
    // when the queue is NOT pinned by a filter forwarding-class AND a BA
    // classifier is configured on the egress interface. A filter-FC-pinned or
    // plain default-queue interface keeps the frozen queue (correct + free).
    let ba_reclassify = fc_queue.is_none()
        && iface.is_some_and(|iface| {
            // #6847: inet-precedence is a per-packet BA classifier like the
            // other two. Leaving it out of this gate would freeze the SEED
            // packet's queue for the flow's lifetime, so a flow whose
            // precedence marking changes mid-flow would keep the first
            // packet's class — classification that silently stops tracking
            // the packets, which is the same defect class as not classifying
            // at all.
            !iface.dscp_classifier.is_empty()
                || !iface.ieee8021_classifier.is_empty()
                || !iface.inet_precedence_classifier.is_empty()
        });

    // #3995: fold the loss-priority-aware CoS rewrite-rule DSCP for the chosen
    // queue (filter DSCP rewrite keeps precedence). The loss-priority derives
    // from the seed packet's ingress DSCP/PCP; for a BA-reclassify flow the
    // frozen queue may shift per packet, so the resolved rewrite reflects the
    // seed packet's queue/loss-priority (correct for the common stable-marking
    // flow; a mixed-marking flow keeps the seed rewrite rather than tracking
    // every packet's loss-priority).
    let cos_rewrite = queue_id.and_then(|queue_id| {
        resolve_cos_queue_lp_rewrite(
            forwarding,
            egress_ifindex,
            queue_id,
            meta.dscp,
            meta.ingress_pcp,
            meta.ingress_vlan_present != 0,
        )
    });

    CachedTxSelectionDescriptor {
        queue_id,
        dscp_rewrite: effective_dscp_rewrite.or(cos_rewrite),
        drop: output_result.action != crate::filter::FilterAction::Accept,
        // #3608: the cached-descriptor `drop` above is the OUTPUT filter's
        // terminal action only (the three-color policer runs separately at
        // replay via `apply_cached_three_color_policers`), so a `drop == true`
        // here is exactly `then discard` or `then reject`. Carry the reject
        // subset so the flow-cache-hit consumer can send an active reply.
        reject: matches!(output_result.action, crate::filter::FilterAction::Reject(_)),
        // #6854: carry the message-type alongside the reject bit so the cached
        // replay sends the code the operator configured, not the default.
        reject_message: if let crate::filter::FilterAction::Reject(m) = output_result.action {
            m
        } else {
            crate::filter::RejectMessage::ADMIN_PROHIBITED
        },
        filter_counters,
        three_color_policers,
        filter_log,
        ba_reclassify,
    }
}

/// #3778: re-resolve the per-packet behavior-aggregate (DSCP / IEEE 802.1p PCP)
/// classifier queue on a flow-cache HIT. The cached TX-selection descriptor
/// froze the SEED packet's queue, but BA classifiers select the egress queue
/// from EACH packet's DSCP / PCP (the flow-cache key excludes both), so a
/// mixed-marking flow would otherwise be pinned to the first packet's queue.
/// Called on the hit path ONLY when the descriptor set `ba_reclassify` (a BA
/// classifier is active AND no filter forwarding-class pinned the queue), so
/// the common no-CoS / filter-FC / default-queue flows never pay for it. One
/// FastMap lookup + two array reads, allocation-free. Precedence matches the
/// seed-time resolution: DSCP classifier, then 802.1p, then default queue.
pub(in crate::afxdp) fn reclassify_cached_ba_queue(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    dscp: u8,
    ingress_pcp: u8,
    ingress_vlan_present: bool,
) -> Option<u8> {
    forwarding
        .cos
        .interfaces
        .get(&egress_ifindex)
        .and_then(|iface| {
            resolve_cos_dscp_classifier_queue_id(iface, dscp)
                .or_else(|| resolve_cos_inet_precedence_classifier_queue_id(iface, dscp))
                .or_else(|| {
                    resolve_cos_ieee8021_classifier_queue_id(iface, ingress_pcp, ingress_vlan_present)
                })
                .or(Some(iface.default_queue))
        })
}

pub(in crate::afxdp) fn resolve_cos_queue_id(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: impl Into<ForwardPacketMeta>,
    flow_key: Option<&SessionKey>,
) -> Option<u8> {
    // #2362 fold B: no frame at this queue-id-only entry; the meta-only extra
    // covers tcp-flags (authoritative in meta) and under-matches is-fragment /
    // icmp-type (acceptable — this path selects a queue, not a security verdict).
    let meta = meta.into();
    let extra = crate::afxdp::frame::term_match_extra_from_meta(meta);
    resolve_cos_tx_selection(forwarding, egress_ifindex, meta, flow_key, extra).queue_id
}

pub(in crate::afxdp) fn resolve_cos_tx_selection(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: impl Into<ForwardPacketMeta>,
    flow_key: Option<&SessionKey>,
    extra: crate::filter::TermMatchExtra,
) -> CoSTxSelection {
    // Non-NAT / single-key callers: ingress input re-walk shares the output tuple.
    resolve_cos_tx_selection_internal(
        forwarding,
        egress_ifindex,
        meta,
        flow_key,
        flow_key,
        extra,
        None,
        None,
    )
}

pub(in crate::afxdp) fn resolve_cos_tx_selection_at(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: impl Into<ForwardPacketMeta>,
    flow_key: Option<&SessionKey>,
    extra: crate::filter::TermMatchExtra,
    now_ns: u64,
) -> CoSTxSelection {
    resolve_cos_tx_selection_internal(
        forwarding,
        egress_ifindex,
        meta,
        flow_key,
        flow_key,
        extra,
        Some(now_ns),
        None,
    )
}

/// #5158: TX-selection variant for the POST-NAT transit forward path. The
/// egress OUTPUT filter and CoS queue selection run on `egress_wire_key` (the
/// post-NAT on-wire tuple, #3642); the ingress INPUT filter re-walk runs on
/// `ingress_flow_key` (the PRE-NAT ingress tuple the input filter originally
/// matched). Callers that build a post-NAT `forward_wire_key` for TX selection
/// (`forward_request`, `neighbor_dispatch` buffered-frame retransmit) pass the
/// pre-NAT session `forward_key` as `ingress_flow_key` so NAT'd traffic still
/// picks up an ingress `then forwarding-class` / dscp-rewrite / three-color
/// policer. `None`/`None` degrades to the flowless path exactly as the single-
/// key entry points do.
pub(in crate::afxdp) fn resolve_cos_tx_selection_at_prenat(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: impl Into<ForwardPacketMeta>,
    egress_wire_key: Option<&SessionKey>,
    ingress_flow_key: Option<&SessionKey>,
    extra: crate::filter::TermMatchExtra,
    now_ns: u64,
    // #7656: post-NAT L3 wire key for the flowless arm; see the internal fn.
    flowless_wire: Option<&SessionKey>,
) -> CoSTxSelection {
    resolve_cos_tx_selection_internal(
        forwarding,
        egress_ifindex,
        meta,
        egress_wire_key,
        ingress_flow_key,
        extra,
        Some(now_ns),
        flowless_wire,
    )
}

fn resolve_cos_tx_selection_internal(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    meta: impl Into<ForwardPacketMeta>,
    flow_key: Option<&SessionKey>,
    ingress_flow_key: Option<&SessionKey>,
    extra: crate::filter::TermMatchExtra,
    now_ns: Option<u64>,
    // #7656: the POST-NAT L3 wire key for a FLOWLESS packet (no `flow_key`).
    // Under NAT64 the packet changes family in flight, so the ingress `meta`
    // fallbacks below select the wrong output-filter family AND match it against
    // the pre-translation addresses and protocol. When the caller can supply the
    // post-NAT tuple, all three reads come from it.
    flowless_wire: Option<&SessionKey>,
) -> CoSTxSelection {
    let meta = meta.into();
    // #3642: an interface `filter output` is applied on the EGRESS interface
    // AFTER NAT, so both the filter FAMILY and the matched tuple must be the
    // POST-NAT (on-wire) ones. Transit callers now pass the post-NAT wire key
    // (`forward_wire_key`) as `flow_key`; its `addr_family` is the egress family
    // — identical to `meta.addr_family` except under NAT64, where the packet
    // changes family. Select the per-family tx-selection gate and the output-
    // filter family from that key so a NAT64 flow evaluates the correct-family
    // output filter against the correct-family tuple. Fall back to the ingress
    // meta family only on the flowless / default-queue path (`flow_key` None).
    // #7656: on the flowless path prefer the POST-NAT wire family over the
    // ingress meta family. This gate selects the per-family tx-selection enable,
    // so a box with v4 tx-selection enabled and v6 not would otherwise
    // short-circuit a NAT64 fragment out of enforcement entirely, before the
    // flowless arm below is ever reached.
    let is_v6 = flow_key
        .or(flowless_wire)
        .map(|key| key.addr_family as i32 == libc::AF_INET6)
        .unwrap_or(meta.addr_family as i32 == libc::AF_INET6);
    let tx_selection_enabled = if is_v6 {
        forwarding.tx_selection_enabled_v6
    } else {
        forwarding.tx_selection_enabled_v4
    };
    if !tx_selection_enabled {
        return CoSTxSelection::default();
    }
    let iface = forwarding.cos.interfaces.get(&egress_ifindex);
    let Some(flow_key) = flow_key else {
        // #hb166 T-6(m): flowless / fragment classification — run the
        // 5-tuple-independent behavior-aggregate (DSCP / 802.1p) lookup from
        // `meta` so a marked fragment lands in its BA queue rather than the
        // default queue. Mirrors the cached-path None branch.
        let queue_id = iface.map(|iface| {
            resolve_cos_dscp_classifier_queue_id(iface, meta.dscp)
                .or_else(|| resolve_cos_inet_precedence_classifier_queue_id(iface, meta.dscp))
                .or_else(|| {
                    resolve_cos_ieee8021_classifier_queue_id(
                        iface,
                        meta.ingress_pcp,
                        meta.ingress_vlan_present != 0,
                    )
                })
                .unwrap_or(iface.default_queue)
        });
        // #3995: flowless packets still resolve the loss-priority-aware CoS
        // rewrite from their own DSCP/PCP (default LOW when unclassified).
        let dscp_rewrite = queue_id.and_then(|queue_id| {
            resolve_cos_queue_lp_rewrite(
                forwarding,
                egress_ifindex,
                queue_id,
                meta.dscp,
                meta.ingress_pcp,
                meta.ingress_vlan_present != 0,
            )
        });
        // #5467: a flowless packet (a non-first IP fragment or a non-query
        // ICMP error/control packet — both carry NO usable L4 ports, #2344 /
        // #3290) still EGRESSES through the interface `filter output`. Before
        // this gate the flowless arm returned `drop:false` WITHOUT ever
        // evaluating the output filter, so an egress `then discard`/`reject`/
        // `log` term that matched such a packet was silently bypassed —
        // fail-OPEN. Evaluate the output filter against the packet's own L3
        // tuple (src/dst/protocol from `meta`; L4 ports forced to 0 since the
        // header is absent) and honor the verdict exactly as the flow-keyed
        // path below does, so an L3-matching deny FAILS CLOSED.
        //
        // Ports are 0, so a port-BEARING output term never matches a fragment
        // (preserving the #2357/#3290 guarantee that a port-matching terminal
        // term does not spuriously drop / misclassify a flowless packet); only
        // an L3-only (`from source-address`/`destination-address`/`protocol`/
        // bare `then`) term takes effect. With no matching output term the
        // result is `drop:false` — the pass-through case is unchanged. Queue
        // and DSCP-rewrite selection stay exactly as computed above; this gate
        // ADDS enforcement only, it does not re-classify the fragment's queue.
        //
        // #7656: family, addresses and protocol all come from the POST-NAT wire
        // key when the caller resolved one, and all from `meta` when it did not.
        // They are read as ONE choice rather than three: a mixture — egress
        // family with ingress addresses — selects the right filter and then
        // cannot match any address-bearing term in it, which is invisible to a
        // fixture whose terms are address-less.
        let (is_v6, wire_l3_addrs, wire_protocol) = match flowless_wire {
            Some(key) => (
                key.addr_family as i32 == libc::AF_INET6,
                Some((key.src_ip, key.dst_ip)),
                key.protocol,
            ),
            None => (
                meta.addr_family as i32 == libc::AF_INET6,
                meta.l3_addrs(),
                meta.protocol,
            ),
        };
        let mut drop = false;
        let mut reject = false;
        // #6854: meaningless unless `reject`; see CoSTxSelection.reject_message.
        let mut reject_message = crate::filter::RejectMessage::ADMIN_PROHIBITED;
        let mut filter_log = None;
        // #6236 PR-2C: fold the `needs_tx_eval` precheck and the output-filter
        // fetch into ONE lookup (see the cached flowless arm above).
        if let Some(output_filter) = crate::filter::interface_output_filter_needing_tx_eval(
            &forwarding.filter_state,
            egress_ifindex,
            is_v6,
        ) && let Some((src_ip, dst_ip)) = wire_l3_addrs
        {
            // Mirror the flow-keyed eval entry points below: ports are 0
            // (L4 absent), `extra` carries the frame-derived is-fragment /
            // l4-present=false predicates so port/flag/icmp-type terms fail
            // closed. The counted variants record `then count` exactly once
            // (this is the only output-filter walk on the flowless path).
            let output_result = if let Some(now_ns) = now_ns {
                crate::filter::evaluate_filter_ref_tx_selection_runtime_counted(
                    output_filter,
                    src_ip,
                    dst_ip,
                    wire_protocol,
                    0,
                    0,
                    meta.dscp,
                    extra,
                    meta.pkt_len as u64,
                    now_ns,
                )
            } else {
                crate::filter::evaluate_filter_ref_tx_selection_counted(
                    output_filter,
                    src_ip,
                    dst_ip,
                    wire_protocol,
                    0,
                    0,
                    meta.dscp,
                    extra,
                    meta.pkt_len as u64,
                )
            };
            // Same collapse as the flow-keyed path: any non-`Accept`
            // terminal action or a three-color-policer drop sets `drop`;
            // `reject` isolates the `then reject` subset. A flowless deny
            // is always a SILENT drop downstream (a fragment has no L4
            // header to synthesize a reply from, #3615) — the caller
            // gates the active reject reply on a real L4 flow.
            drop = output_result.policer_drop
                || output_result.action != crate::filter::FilterAction::Accept;
            reject = matches!(output_result.action, crate::filter::FilterAction::Reject(_));
            reject_message = if let crate::filter::FilterAction::Reject(m) = output_result.action {
                m
            } else {
                crate::filter::RejectMessage::ADMIN_PROHIBITED
            };
            filter_log = output_result.log_match;
        }
        return CoSTxSelection {
            queue_id,
            dscp_rewrite,
            drop,
            reject,
            reject_message,
            filter_log,
        };
    };
    // `is_v6` derived above from the (post-NAT) egress key, not `meta` (#3642).
    // #5158: the ingress INPUT filter matched the packet on its PRE-NAT ingress
    // tuple (Junos applies input filters BEFORE NAT), so its re-walk below runs
    // on the pre-NAT `ingress_flow_key` and the ingress-side family, NOT the
    // post-NAT egress wire key `flow_key`/`is_v6`. For a non-NAT flow both keys —
    // and both families — match, so this is a no-op there.
    let ingress_key = ingress_flow_key.unwrap_or(flow_key);
    let ingress_is_v6 = ingress_key.addr_family as i32 == libc::AF_INET6;
    // #6236 PR-2C: one lookup for both the gate and the walk (see the cached
    // flow-keyed arm above). The PR-2A `has_output_needs_tx_eval_*` aggregate
    // (`tx_selection_enabled`) already short-circuited the whole path upstream.
    let output_filter = crate::filter::interface_output_filter_needing_tx_eval(
        &forwarding.filter_state,
        egress_ifindex,
        is_v6,
    );
    let has_output_tx_eval = output_filter.is_some();
    let has_input_tx_selection =
        crate::filter::filter_state_has_input_tx_selection(&forwarding.filter_state, ingress_is_v6);
    let has_input_three_color_policer =
        crate::filter::filter_state_has_input_three_color_policer(
            &forwarding.filter_state,
            ingress_is_v6,
        );
    if iface.is_none()
        && !has_output_tx_eval
        && !has_input_tx_selection
        && !has_input_three_color_policer
    {
        return CoSTxSelection {
            queue_id: None,
            dscp_rewrite: None,
            drop: false,
            reject: false,
            reject_message: crate::filter::RejectMessage::ADMIN_PROHIBITED,
            filter_log: None,
        };
    }
    // #hb166 T-3: evaluate the INGRESS input filter for its forwarding-class /
    // dscp-rewrite whenever an input tx-selection filter (or an input
    // three-color policer) exists — INCLUDING when an OUTPUT filter is also
    // attached. Junos semantics are output-OVERRIDES-when-set, not
    // output-PRESENCE-clears-ingress: a counter/log/terminal-only output filter
    // with no `then forwarding-class` must NOT wipe the class an input filter
    // assigned. The output result still wins when it sets a class (resolved
    // first below); the ingress class only fills the gap. The `then count`
    // double-count is already avoided by the counter-suppressed ingress variant
    // (#4085), so evaluating the ingress leg here is side-effect free.
    let need_ingress_eval = has_input_tx_selection || has_input_three_color_policer;
    let ingress_ifindex = if need_ingress_eval {
        resolve_ingress_logical_ifindex(
            forwarding,
            meta.ingress_ifindex as i32,
            meta.ingress_vlan_id,
        )
        .unwrap_or(meta.ingress_ifindex as i32)
    } else {
        0
    };
    let ingress_filter = if need_ingress_eval {
        if ingress_is_v6 {
            forwarding
                .filter_state
                .iface_filter_v6_fast
                .get(&ingress_ifindex)
                .map(Arc::as_ref)
        } else {
            forwarding
                .filter_state
                .iface_filter_v4_fast
                .get(&ingress_ifindex)
                .map(Arc::as_ref)
        }
    } else {
        None
    };
    // #6236 PR-2C: `output_filter` is already gated on `needs_tx_eval()` by
    // `interface_output_filter_needing_tx_eval`, so no second `.filter()`.
    let output_result = if let Some(output_filter) = output_filter {
        if let Some(now_ns) = now_ns {
            crate::filter::evaluate_filter_ref_tx_selection_runtime_counted(
                output_filter,
                flow_key.src_ip,
                flow_key.dst_ip,
                flow_key.protocol,
                flow_key.src_port,
                flow_key.dst_port,
                meta.dscp,
                extra,
                meta.pkt_len as u64,
                now_ns,
            )
        } else {
            crate::filter::evaluate_filter_ref_tx_selection_counted(
                output_filter,
                flow_key.src_ip,
                flow_key.dst_ip,
                flow_key.protocol,
                flow_key.src_port,
                flow_key.dst_port,
                meta.dscp,
                extra,
                meta.pkt_len as u64,
            )
        }
    } else {
        crate::filter::TxSelectionFilterResult::default()
    };
    let mut effective_dscp_rewrite = output_result.dscp_rewrite;
    let mut drop =
        output_result.policer_drop || output_result.action != crate::filter::FilterAction::Accept;
    // #3608: isolate the `then reject` subset of the collapsed `drop` bit so the
    // TX/CoS consumer can synthesize an active reject reply. Only the OUTPUT
    // filter's terminal action produces a reject; a three-color-policer drop
    // (`policer_drop`, above or the ingress meter below) is always a silent
    // discard.
    let reject = matches!(output_result.action, crate::filter::FilterAction::Reject(_));
    let reject_message = if let crate::filter::FilterAction::Reject(m) = output_result.action {
            m
    } else {
            crate::filter::RejectMessage::ADMIN_PROHIBITED
    };
    let mut ingress_forwarding_class = None;
    let filter_log = output_result.log_match;
    if let Some(ingress_filter) = ingress_filter.filter(|filter| {
        filter.affects_tx_selection || filter.has_three_color_policer_terms
    }) {
        // #4085: the INGRESS input filter's `then count` terms are already
        // recorded exactly once by the input-filter ACTION evaluation
        // (`evaluate_non_pbr_input_filter` on the session-miss / DSCP-sensitive
        // session-hit path) and, for a cacheable flow, replayed on hits from the
        // cached filter_counter set. This tx-selection re-walk exists ONLY to
        // extract forwarding-class / dscp-rewrite for queue selection and to
        // METER the ingress three-color policer, so it MUST NOT re-record the
        // count — use the counter-suppressed variant (the policer meter still
        // runs via the threaded now_ns).
        // #5158: re-walk on the PRE-NAT ingress tuple, not `flow_key` (the
        // post-NAT egress wire key the output filter used above).
        let ingress_result = if let Some(now_ns) = now_ns {
            crate::filter::evaluate_filter_ref_tx_selection_runtime_uncounted(
                ingress_filter,
                ingress_key.src_ip,
                ingress_key.dst_ip,
                ingress_key.protocol,
                ingress_key.src_port,
                ingress_key.dst_port,
                meta.dscp,
                extra,
                meta.pkt_len as u64,
                now_ns,
            )
        } else {
            crate::filter::evaluate_filter_ref_tx_selection_uncounted(
                ingress_filter,
                ingress_key.src_ip,
                ingress_key.dst_ip,
                ingress_key.protocol,
                ingress_key.src_port,
                ingress_key.dst_port,
                meta.dscp,
                extra,
                meta.pkt_len as u64,
            )
        };
        effective_dscp_rewrite = effective_dscp_rewrite.or(ingress_result.dscp_rewrite);
        drop |= ingress_result.policer_drop;
        // #hb166 T-3: always capture the ingress forwarding-class. The resolver
        // below tries the OUTPUT filter's class FIRST, so a `then
        // forwarding-class` on the output filter still wins; the ingress class
        // is only consulted when the output filter set none (or is absent).
        ingress_forwarding_class = ingress_result.forwarding_class;
    }
    let Some(iface) = iface else {
        return CoSTxSelection {
            queue_id: None,
            dscp_rewrite: effective_dscp_rewrite,
            drop,
            reject,
            reject_message,
            filter_log,
        };
    };
    // Queue selection precedence: the output-filter forwarding-class, then the
    // ingress input-filter forwarding-class, then the DSCP behavior-aggregate
    // classifier, then the IP-precedence classifier (#6847), then the 802.1p
    // classifier, then the interface default queue.
    //
    // DSCP before inet-precedence is load-bearing, not incidental: the two read
    // the same DS field, so a unit binding both is rejected at commit
    // (validateCoSUnitClassifierConflict) — but the tolerant Load / peer-sync
    // path downgrades that to a warning so an already-persisted config still
    // boots (#1960). On that boot this order is what makes "DSCP wins" true,
    // which is what the Go warning tells the operator will happen. Both L3
    // arms precede the L2 802.1p arm.
    let queue_id = output_result
        .forwarding_class
        .and_then(|forwarding_class| iface.queue_by_forwarding_class.get(forwarding_class).copied())
        .or_else(|| {
            ingress_forwarding_class.and_then(|forwarding_class| {
                iface.queue_by_forwarding_class.get(forwarding_class).copied()
            })
        })
        .or_else(|| resolve_cos_dscp_classifier_queue_id(iface, meta.dscp))
        .or_else(|| resolve_cos_inet_precedence_classifier_queue_id(iface, meta.dscp))
        .or_else(|| {
            resolve_cos_ieee8021_classifier_queue_id(
                iface,
                meta.ingress_pcp,
                meta.ingress_vlan_present != 0,
            )
        })
        .unwrap_or(iface.default_queue);
    // #3995: fold the loss-priority-aware CoS rewrite-rule DSCP for the chosen
    // queue. A filter DSCP rewrite (`effective_dscp_rewrite`) still takes
    // precedence; the CoS rewrite-rule only fills the gap, matching the drain
    // ordering `req.dscp_rewrite.or(queue_dscp_rewrite)` this replaces.
    let cos_rewrite = resolve_cos_queue_lp_rewrite(
        forwarding,
        egress_ifindex,
        queue_id,
        meta.dscp,
        meta.ingress_pcp,
        meta.ingress_vlan_present != 0,
    );
    CoSTxSelection {
        queue_id: Some(queue_id),
        dscp_rewrite: effective_dscp_rewrite.or(cos_rewrite),
        drop,
        reject,
        reject_message,
        filter_log,
    }
}

/// #3995: resolve THIS packet's classifier-assigned loss-priority on the egress
/// interface (index 0=low .. 3=high). Mirrors the BA queue-selection order —
/// the DSCP classifier first, then 802.1p (when the frame carries a VLAN tag),
/// then the Junos default LOW for an unclassified code-point.
fn resolve_cos_loss_priority(
    lp: &CoSLossPriorityRewrite,
    dscp: u8,
    ingress_pcp: u8,
    vlan_present: bool,
) -> u8 {
    let dscp_lp = lp.dscp_lp_by_dscp[usize::from(dscp & 0x3f)];
    if dscp_lp != u8::MAX {
        return dscp_lp;
    }
    // #6847: the IP-precedence classifier's loss-priority, in the same position
    // in the chain as its queue arm. Skipping this would accept
    // `loss-priority high` on an inet-precedence entry at commit and then apply
    // the LOW rewrite on egress — an accepted-but-inert knob of exactly the
    // kind #6847 removes from the queue side.
    let prec_lp = lp.inet_precedence_lp_by_prec[usize::from((dscp >> 3) & 0x7)];
    if prec_lp != u8::MAX {
        return prec_lp;
    }
    if vlan_present {
        if let Some(&pcp_lp) = lp.ieee8021_lp_by_pcp.get(usize::from(ingress_pcp)) {
            if pcp_lp != u8::MAX {
                return pcp_lp;
            }
        }
    }
    0
}

/// #3995: resolve the egress DSCP rewrite for (this packet's egress queue, this
/// packet's classifier loss-priority). Returns `None` when the interface has no
/// loss-priority rewrite tables, or the (queue, loss-priority) pair has no
/// configured code-point — so the caller keeps any filter DSCP rewrite / no
/// rewrite. This is deterministic per flow (the loss-priority derives from the
/// flow's ingress code-point) and is therefore cached per-flow exactly like the
/// pre-existing filter DSCP rewrite.
fn resolve_cos_queue_lp_rewrite(
    forwarding: &ForwardingState,
    egress_ifindex: i32,
    queue_id: u8,
    dscp: u8,
    ingress_pcp: u8,
    vlan_present: bool,
) -> Option<u8> {
    let lp = forwarding.cos.lp_rewrite.get(&egress_ifindex)?;
    let plp = resolve_cos_loss_priority(lp, dscp, ingress_pcp, vlan_present);
    lp.dscp_rewrite_by_queue_lp.get(&(queue_id, plp)).copied()
}

fn resolve_cos_dscp_classifier_queue_id(iface: &CoSInterfaceConfig, dscp: u8) -> Option<u8> {
    let queue_id = iface.dscp_queue_by_dscp[usize::from(dscp & 0x3f)];
    (queue_id != u8::MAX).then_some(queue_id)
}

/// #6847: resolve the queue for this packet's IP precedence — the top 3 bits of
/// the DS field, i.e. `(dscp >> 3)` where `dscp` is already the 6-bit field the
/// frame parser extracted (`packet[1] >> 2` for IPv4 TOS, `traffic_class >> 2`
/// for IPv6). The `& 0x7` is belt: a 6-bit input cannot exceed 7 after the
/// shift, but the mask makes the 8-entry table index total regardless of what
/// a future parser change puts in `meta.dscp`.
///
/// Family-agnostic, exactly like `resolve_cos_dscp_classifier_queue_id` above
/// — this codebase has never split the DS-field classifier by address family
/// (Junos models `dscp` and `dscp-ipv6` separately; we do not), and adding the
/// split for inet-precedence alone would be a new inconsistency.
fn resolve_cos_inet_precedence_classifier_queue_id(
    iface: &CoSInterfaceConfig,
    dscp: u8,
) -> Option<u8> {
    let queue_id = iface.inet_precedence_queue_by_prec[usize::from((dscp >> 3) & 0x7)];
    (queue_id != u8::MAX).then_some(queue_id)
}

fn resolve_cos_ieee8021_classifier_queue_id(
    iface: &CoSInterfaceConfig,
    pcp: u8,
    vlan_present: bool,
) -> Option<u8> {
    if !vlan_present {
        return None;
    }
    // #hb166 T-7: fail-closed on an out-of-range PCP instead of the
    // pre-fix `pcp.min(7)` clamp, which silently misclassified any value
    // >7 as the PCP-7 traffic class — the exact fail-OPEN the #2447
    // build-side gate refuses (see forwarding_build/cos.rs). The wire PCP
    // field is structurally 3-bit, so this guards only a malformed shim
    // meta / version drift: a bad value falls through to the default
    // queue (None) rather than being routed to the wrong class.
    let queue_id = *iface.ieee8021_queue_by_pcp.get(usize::from(pcp))?;
    (queue_id != u8::MAX).then_some(queue_id)
}

pub(in crate::afxdp) fn enqueue_local_into_cos(
    binding: &mut BindingWorker,
    forwarding: &ForwardingState,
    req: TxRequest,
    now_ns: u64,
    mut shared_recycles: Option<&mut Vec<(u32, u64)>>,
) -> Result<(), TxRequest> {
    let egress_ifindex = req.egress_ifindex;
    if !ensure_cos_interface_runtime(binding, forwarding, egress_ifindex, now_ns) {
        return Err(req);
    }
    if binding
        .cos
        .cos_interfaces
        .get(&egress_ifindex)
        .is_some_and(|root| cos_queue_accepts_prepared(root, req.cos_queue_id))
    {
        match prepare_local_request_for_cos(
            binding.umem.area(),
            &mut binding.tx_pipeline.free_tx_frames,
            req,
        ) {
            Ok(prepared_req) => {
                let item_len = prepared_req.len as u64;
                match enqueue_cos_item(
                    binding,
                    egress_ifindex,
                    prepared_req.cos_queue_id,
                    item_len,
                    CoSPendingTxItem::Prepared(prepared_req),
                    now_ns,
                    shared_recycles.as_deref_mut(),
                ) {
                    Ok(()) => return Ok(()),
                    Err(CoSPendingTxItem::Prepared(mut prepared_req)) => {
                        // #8597 K41: NEVER panic on the TX path.
                        //
                        // `clone_prepared_request_for_cos` returns None only
                        // when `area.slice(offset, len)` refuses -- a prepared
                        // descriptor pointing outside the UMEM, i.e. corruption.
                        // `.expect()` turned that into a worker panic, and a
                        // panicked TX worker is a fail-closed stall with no
                        // restart (the supervisor is detection-only), so one
                        // bad descriptor took down every flow on that worker.
                        //
                        // Dropping the packet is strictly better and is what a
                        // corrupt descriptor deserves: the frame is recycled so
                        // the UMEM slot is not leaked, and the drop is
                        // attributed rather than silent.
                        //
                        // `tx_errors` is the right counter here and that is
                        // deliberate, not incidental: the convention at the foot
                        // of this file reserves it for FAULTS and keeps DESIGNED
                        // shaping drops off it (`admission_*_drops` /
                        // `dbg_cos_queue_overflow`). An out-of-bounds descriptor
                        // is a fault.
                        let Some(req) =
                            clone_prepared_request_for_cos(binding.umem.area(), &mut prepared_req)
                        else {
                            binding
                                .live
                                .tx_errors
                                .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                            recycle_prepared_immediately_with_shared(
                                binding,
                                &prepared_req,
                                shared_recycles.as_deref_mut(),
                            );
                            return Ok(());
                        };
                        recycle_prepared_immediately_with_shared(
                            binding,
                            &prepared_req,
                            shared_recycles.as_deref_mut(),
                        );
                        let item_len = req.bytes.len() as u64;
                        return match enqueue_cos_item(
                            binding,
                            egress_ifindex,
                            req.cos_queue_id,
                            item_len,
                            CoSPendingTxItem::Local(req),
                            now_ns,
                            shared_recycles.as_deref_mut(),
                        ) {
                            Ok(()) => Ok(()),
                            Err(CoSPendingTxItem::Local(req)) => Err(req),
                            Err(CoSPendingTxItem::Prepared(_)) => {
                                unreachable!("local request returned prepared item")
                            }
                        };
                    }
                    Err(CoSPendingTxItem::Local(_)) => {
                        unreachable!("local request prepared into prepared item")
                    }
                }
            }
            Err(req) => {
                // Fall through to the local CoS path when no TX frame is
                // available or the request cannot be materialized safely.
                let area = binding.umem.area();
                let slot = binding.slot;
                if let Some(root) = binding.cos.cos_interfaces.get_mut(&egress_ifindex) {
                    let _ = demote_prepared_cos_queue_to_local(
                        area,
                        &mut binding.tx_pipeline.free_tx_frames,
                        &mut binding.tx_pipeline.pending_fill_frames,
                        slot,
                        root,
                        req.cos_queue_id,
                        shared_recycles.as_deref_mut(),
                    );
                }
                let req = req;
                let item_len = req.bytes.len() as u64;
                return match enqueue_cos_item(
                    binding,
                    egress_ifindex,
                    req.cos_queue_id,
                    item_len,
                    CoSPendingTxItem::Local(req),
                    now_ns,
                    shared_recycles.as_deref_mut(),
                ) {
                    Ok(()) => Ok(()),
                    Err(CoSPendingTxItem::Local(req)) => Err(req),
                    Err(CoSPendingTxItem::Prepared(_)) => {
                        unreachable!("local request returned prepared item")
                    }
                };
            }
        }
    }
    let item_len = req.bytes.len() as u64;
    match enqueue_cos_item(
        binding,
        egress_ifindex,
        req.cos_queue_id,
        item_len,
        CoSPendingTxItem::Local(req),
        now_ns,
        shared_recycles.as_deref_mut(),
    ) {
        Ok(()) => Ok(()),
        Err(CoSPendingTxItem::Local(req)) => Err(req),
        Err(CoSPendingTxItem::Prepared(_)) => unreachable!("local request returned prepared item"),
    }
}

pub(super) fn prepare_local_request_for_cos(
    area: &MmapArea,
    free_tx_frames: &mut VecDeque<u64>,
    req: TxRequest,
) -> Result<PreparedTxRequest, TxRequest> {
    if req.bytes.len() > tx_frame_capacity() {
        return Err(req);
    }
    if req.mirror_clone && free_tx_frames.len() <= MIRROR_TX_FRAME_RESERVE {
        return Err(req);
    }
    let Some(offset) = free_tx_frames.pop_front() else {
        return Err(req);
    };
    let Some(frame) = (unsafe { area.slice_mut_unchecked(offset as usize, req.bytes.len()) })
    else {
        free_tx_frames.push_front(offset);
        return Err(req);
    };
    frame.copy_from_slice(&req.bytes);
    Ok(req.into_prepared_request(offset, PreparedTxRecycle::FreeTxFrame))
}

pub(super) fn enqueue_prepared_into_cos(
    binding: &mut BindingWorker,
    forwarding: &ForwardingState,
    mut req: PreparedTxRequest,
    now_ns: u64,
    mut shared_recycles: Option<&mut Vec<(u32, u64)>>,
) -> Result<(), PreparedTxRequest> {
    let egress_ifindex = req.egress_ifindex;
    if !ensure_cos_interface_runtime(binding, forwarding, egress_ifindex, now_ns) {
        return Err(req);
    }
    if binding
        .cos
        .cos_interfaces
        .get(&egress_ifindex)
        .is_some_and(|root| cos_queue_accepts_prepared(root, req.cos_queue_id))
    {
        let item_len = req.len as u64;
        match enqueue_cos_item(
            binding,
            egress_ifindex,
            req.cos_queue_id,
            item_len,
            CoSPendingTxItem::Prepared(req),
            now_ns,
            shared_recycles.as_deref_mut(),
        ) {
            Ok(()) => return Ok(()),
            Err(CoSPendingTxItem::Prepared(req)) => return Err(req),
            Err(CoSPendingTxItem::Local(_)) => unreachable!("prepared request returned local item"),
        }
    }

    let Some(local_req) = clone_prepared_request_for_cos(binding.umem.area(), &mut req) else {
        return Err(req);
    };
    // Keep prepared/direct frames in CoS while a queue stays prepared-only.
    // Once any copied local item enters that queue, later prepared frames must
    // fall back to local copies until the queue drains empty again; otherwise a
    // local head item can block behind prepared frames that are holding every
    // free TX frame on the owner binding.
    let item_len = local_req.bytes.len() as u64;
    match enqueue_cos_item(
        binding,
        egress_ifindex,
        local_req.cos_queue_id,
        item_len,
        CoSPendingTxItem::Local(local_req),
        now_ns,
        shared_recycles.as_deref_mut(),
    ) {
        Ok(()) => {
            recycle_prepared_immediately_with_shared(binding, &req, shared_recycles.as_deref_mut());
            Ok(())
        }
        Err(CoSPendingTxItem::Local(mut local_req)) => {
            req.overlap_admissions = local_req.overlap_admissions.take();
            Err(req)
        }
        Err(CoSPendingTxItem::Prepared(_)) => {
            unreachable!("prepared queueing converted to local request")
        }
    }
}

pub(super) fn clone_prepared_request_for_cos(
    area: &MmapArea,
    req: &mut PreparedTxRequest,
) -> Option<TxRequest> {
    let frame = area.slice(req.offset as usize, req.len as usize)?.to_vec();
    Some(req.into_local_request(frame))
}

pub(super) fn resolve_cos_queue_idx(
    root: &CoSInterfaceRuntime,
    requested_queue: Option<u8>,
) -> Option<usize> {
    if root.queues.is_empty() {
        return None;
    }
    // The default-queue index. `queues` is non-empty here, so index 0 is always
    // a valid fallback when the interface has no queue tagged as its
    // `default_queue`.
    let default_idx = || {
        root.queues
            .iter()
            .position(|queue| queue.queue_id() == root.default_queue)
            .unwrap_or(0)
    };
    if let Some(queue_id) = requested_queue {
        // #hb166 T-4: a requested queue that this interface does not
        // materialize (e.g. a BA classifier code-point steering to a
        // forwarding-class with no scheduler-map entry, or a cached descriptor
        // that froze a queue id which a later config drop un-materialized) MUST
        // fall back to the default/best-effort queue — forward on best-effort,
        // NEVER blackhole. Pre-fix `position()` returned `None` for an
        // unmaterialized queue, and the sole enqueue caller turned that `None`
        // into an `Err` → drop. The build-time classifier table (#hb166 T-4 in
        // forwarding_build/cos.rs) already substitutes the default queue, so
        // this runtime fallback is the belt-and-suspenders second layer.
        return Some(
            root.queues
                .iter()
                .position(|queue| queue.queue_id() == queue_id)
                .unwrap_or_else(default_idx),
        );
    }
    Some(default_idx())
}

/// Put back the MQFQ frontier snapshot taken before `cos_queue_drain_all`
/// (#926, all exits since #9066).
///
/// Extracted so the success path and BOTH failure paths cannot drift: the
/// failure paths used to skip it on the stated ground that
/// `cos_queue_restore_front` is "round-trip neutral per #913 §3.7". It is —
/// for ONE bucket. Across several, each bucket's frontier comes back inflated
/// by the bytes of the other buckets drained ahead of its own last item, so a
/// flow arriving right after a failed demote anchors at `vtime + bytes` and is
/// served ahead of the whole restored backlog.
///
/// A no-op when nothing was saved (no flow-fair state), which is the
/// single-bucket-configuration case and the reason this went unnoticed.
fn restore_flow_fair_frontier(
    queue: &mut CoSQueueRuntime,
    saved: Option<(u64, [u64; COS_FLOW_FAIR_BUCKETS], [u64; COS_FLOW_FAIR_BUCKETS])>,
) {
    if let (Some(ff), Some((saved_queue_vtime, saved_head_finish, saved_tail_finish))) =
        (queue.flow_fair_state.as_mut(), saved)
    {
        ff.queue_vtime = saved_queue_vtime;
        ff.flow_bucket_head_finish_bytes = saved_head_finish;
        ff.flow_bucket_tail_finish_bytes = saved_tail_finish;
    }
}

pub(in crate::afxdp) fn demote_prepared_cos_queue_to_local(
    area: &MmapArea,
    free_tx_frames: &mut VecDeque<u64>,
    pending_fill_frames: &mut VecDeque<u64>,
    slot: u32,
    root: &mut CoSInterfaceRuntime,
    requested_queue: Option<u8>,
    mut shared_recycles: Option<&mut Vec<(u32, u64)>>,
) -> bool {
    let Some(queue_idx) = resolve_cos_queue_idx(root, requested_queue) else {
        return false;
    };
    let Some(queue) = root.queues.get_mut(queue_idx) else {
        return false;
    };
    if !queue.config.exact || cos_queue_is_empty(queue) {
        return false;
    }
    // #926: snapshot MQFQ frontier state BEFORE drain_all so we
    // can restore on the success path. cos_queue_drain_all uses
    // the no-snapshot pop variant (aggregate-bytes vtime advance:
    // queue_vtime += bytes per pop) which inflates queue_vtime
    // by the entire drained backlog. cos_queue_push_back then
    // re-anchors finish-times against the inflated vtime
    // (max(tail, queue_vtime) + bytes), letting any new flow Y
    // enqueued immediately after demotion jump ahead of the
    // demoted backlog — the temporal-inversion bug class #911 /
    // #913 was supposed to prevent.
    //
    // #9066: this comment used to end "The failure-rollback path
    // (cos_queue_restore_front) is round-trip neutral per #913
    // §3.7 and stays correct without snapshot/restore." THAT IS
    // TRUE FOR A SINGLE BUCKET AND FALSE FOR SEVERAL. Measured on
    // three flows x two packets at vtime 5000, forced down the
    // Local-head `else` arm: bucket head_finish moved +4200,
    // +2700 and +3300 respectively, because each bucket's frontier
    // is inflated by the bytes of the OTHER buckets drained ahead
    // of its own last item. vtime round-trips exactly and the
    // relative order among restored buckets survives, so this is
    // not "corrupt scheduler state" — what it is, is a NEWCOMER
    // anchoring at vtime + bytes and being served ahead of the
    // entire restored backlog. That is #926's temporal inversion,
    // fixed on the success path and left open on the failure one.
    //
    // The restore now runs on ALL THREE exits (see
    // restore_flow_fair_frontier below). The single-bucket cell
    // mqfq_push_front_is_neutral_on_drained_bucket_round_trip
    // cannot see this by construction — with one bucket there are
    // no other buckets to drain ahead of it.
    //
    // Single-worker invariant (Gemini R2): demote and pop run
    // in the same worker thread, and any in-flight pop's
    // snapshot is cleared by cos_queue_drain_all below
    // (cos_queue_drain_all). So no cross-batch pop_snapshot_stack
    // entries can be live at this point — restoring vtime +
    // head/tail finish-times can't race with a concurrent
    // pop's snapshot interpretation.
    //
    // Footprint: 64 KB stack memcpy of two [u64; COS_FLOW_FAIR_BUCKETS]
    // arrays (32 KB each at 4096 buckets — the #785 fairness
    // bump from 1024). Both are already cache-resident in the queue;
    // demote is a rare TX-frame-exhaustion fallback called from
    // tx/cos_classify.rs::enqueue_local_into_cos, not a hot-path operation.
    let saved_flow_fair_frontier = queue.flow_fair_state.as_ref().map(|ff| {
        (
            ff.queue_vtime,
            ff.flow_bucket_head_finish_bytes,
            ff.flow_bucket_tail_finish_bytes,
        )
    });
    let mut drained = cos_queue_drain_all(queue);
    let mut local_items = VecDeque::with_capacity(drained.len());
    let mut recycles = Vec::with_capacity(drained.len());
    for item in &mut drained {
        let CoSPendingTxItem::Prepared(req) = item else {
            cos_queue_restore_front(queue, drained);
            // #9066: the frontier restore runs here too. cos_queue_restore_front
            // is NOT round-trip neutral across multiple buckets.
            restore_flow_fair_frontier(queue, saved_flow_fair_frontier);
            return false;
        };
        let Some(local_req) = clone_prepared_request_for_cos(area, req) else {
            cos_queue_restore_front(queue, drained);
            restore_flow_fair_frontier(queue, saved_flow_fair_frontier);
            return false;
        };
        local_items.push_back(CoSPendingTxItem::Local(local_req));
        recycles.push((req.recycle, req.offset));
    }
    for item in local_items {
        cos_queue_push_back(queue, item);
    }
    for (recycle, offset) in recycles {
        recycle_cancelled_prepared_offset_with_shared(
            free_tx_frames,
            pending_fill_frames,
            shared_recycles.as_deref_mut(),
            slot,
            recycle,
            offset,
        );
    }

    // #926: restore MQFQ frontier on the success path. Same
    // flow_keys → same cos_flow_bucket_index → same buckets,
    // so the saved per-bucket head/tail finish-times still
    // apply. Restoring queue_vtime alongside keeps the three
    // values internally consistent.
    restore_flow_fair_frontier(queue, saved_flow_fair_frontier);

    // #940: explicit V_min publish after the demote restore. The
    // pop-time publish was removed in #940; without this hook,
    // peers would never see the post-demote state — the slot stays
    // at whatever was published BEFORE this demote ran. Publishing
    // the saved (== restored) vtime is correct and idempotent
    // (matches the value peers saw before demote).
    //
    // Sequencing invariant (Gemini review): demote runs from
    // `enqueue_local_into_cos` on the rx/producer path BEFORE any
    // post-settle publish for THIS queue in this worker iteration.
    // The saved `queue_vtime` (line 5512 area) therefore equals the
    // value that the previous iteration's post-settle publish
    // broadcast to this slot. drain_all inflates `queue_vtime`
    // locally; restore at lines 5582-5584 puts it back to the saved
    // value; this publish broadcasts the same value again. Net
    // effect on peers: slot-value unchanged. No "rewind" possible
    // because the worker's per-iteration rx-then-tx ordering
    // serializes demote (rx path) before the in-flight tx batch's
    // settle.
    publish_committed_queue_vtime(Some(&*queue));

    true
}

/// #774: O(1) check replacing the prior O(n) scan. Profiled at
/// 3.25% CPU on the hot path at line rate before this fix.
/// `local_item_count` is maintained at every push/pop site in
/// `cos_queue_push_*` / `cos_queue_pop_front`. Single-writer
/// (owner worker), same discipline as `queued_bytes` — no atomic
/// needed.
#[inline]
pub(in crate::afxdp) fn cos_queue_accepts_prepared(
    root: &CoSInterfaceRuntime,
    requested_queue: Option<u8>,
) -> bool {
    let Some(queue_idx) = resolve_cos_queue_idx(root, requested_queue) else {
        return false;
    };
    let Some(queue) = root.queues.get(queue_idx) else {
        return false;
    };
    queue.hot.local_item_count == 0
}

pub(in crate::afxdp) fn cos_queue_dscp_rewrite(
    binding: &BindingWorker,
    root_ifindex: i32,
    queue_idx: usize,
) -> Option<u8> {
    binding
        .cos
        .cos_interfaces
        .get(&root_ifindex)
        .and_then(|root| root.queues.get(queue_idx))
        .and_then(|queue| queue.config.dscp_rewrite)
}

fn enqueue_cos_item(
    binding: &mut BindingWorker,
    egress_ifindex: i32,
    requested_queue: Option<u8>,
    item_len: u64,
    mut item: CoSPendingTxItem,
    now_ns: u64,
    mut shared_recycles: Option<&mut Vec<(u32, u64)>>,
) -> Result<(), CoSPendingTxItem> {
    // #1829 Phase 1: stamp the CoS enqueue timestamp at the single
    // admission choke point. Every item entering a CoS queue passes
    // through here exactly once per admission attempt; promote
    // migrations and pop->push_front rollbacks re-insert via
    // `cos_queue_push_back`/`cos_queue_push_front` directly and
    // therefore keep the ORIGINAL stamp (correct for sojourn). One
    // u64 store from the already-threaded pass `now_ns` -- no clock
    // syscall (#1734).
    match &mut item {
        CoSPendingTxItem::Local(req) => req.enqueue_ns = now_ns,
        CoSPendingTxItem::Prepared(req) => req.enqueue_ns = now_ns,
    }
    let mut root_became_nonempty = false;
    let mut accepted_exact = false;
    let (accepted, _queue_id, recycle) = {
        // Split-borrow: `umem` sits alongside `cos_interfaces` on
        // `BindingWorker`, so we can take a shared borrow on the umem
        // field while holding `&mut binding.cos.cos_interfaces` for the
        // admission-gate block. The Prepared-variant ECN marker
        // (#727) needs this to mutate frame bytes in the UMEM
        // in-place; the admission gate runs strictly before the
        // frame is enqueued, so nothing else in the system observes
        // the bytes concurrently. Both fields are borrowed explicitly
        // here so the borrow checker keeps us honest.
        let umem = binding.umem.area();
        let Some(root) = binding.cos.cos_interfaces.get_mut(&egress_ifindex) else {
            return Err(item);
        };
        // #hb166 T-4: `resolve_cos_queue_idx` always returns a `position()` into
        // `root.queues` (or `None` only when the interface has no queues at
        // all), so the resolved index is in-bounds by construction. The prior
        // `if queue_idx >= root.queues.len() { queue_idx = 0; }` clamp was
        // dead code that implied a fallback the resolver did not actually
        // provide for an unmaterialized requested queue — the real fallback now
        // lives inside `resolve_cos_queue_idx` (default-queue substitution).
        let Some(queue_idx) = resolve_cos_queue_idx(root, requested_queue) else {
            return Err(item);
        };
        let root_was_empty = root.nonempty_queues == 0;
        let queue = &mut root.queues[queue_idx];
        // #707: aggregate cap scales with prospective-active flow count
        // so the per-flow fast-retransmit floor can be satisfied, and
        // the aggregate gate uses the same denominator as the per-flow
        // clamp — otherwise the first packet of a new flow can get
        // stuck at the boundary even when the per-flow path is trying
        // to admit it. Compute `flow_bucket` once so both gates key off
        // the same queue state snapshot.
        let flow_bucket = if queue.flow_fair() {
            let ff = queue
                .flow_fair_state
                .as_ref()
                .expect("flow_fair queue missing FlowFairState");
            cos_flow_bucket_index(ff.flow_hash_seed, cos_item_flow_key(&item))
        } else {
            0
        };
        let buffer_limit = cos_flow_aware_buffer_limit(queue, flow_bucket);
        let flow_share_exceeded = if queue.flow_fair() {
            let ff = queue
                .flow_fair_state
                .as_ref()
                .expect("flow_fair queue missing FlowFairState");
            ff.flow_bucket_bytes[flow_bucket].saturating_add(item_len)
                > cos_queue_flow_share_limit(queue, buffer_limit, flow_bucket)
        } else {
            false
        };
        let buffer_exceeded = queue.hot.queued_bytes.saturating_add(item_len) > buffer_limit;
        // #718 + #722: ECN CE-mark above threshold so ECN-negotiated
        // TCP flows back off smoothly rather than tail-dropping into
        // RTO. Non-ECT packets are untouched — they fall back to the
        // existing admission drop path below. Mark only when the
        // packet will actually be admitted: a marked-and-then-dropped
        // packet wastes both the mark and the bandwidth the mark was
        // trying to steer. `flow_bucket` is the same index the
        // per-flow admission gate keyed off, so both gates see the
        // same queue snapshot.
        let _ = apply_cos_admission_ecn_policy(
            queue,
            buffer_limit,
            flow_bucket,
            flow_share_exceeded,
            buffer_exceeded,
            &mut item,
            umem,
        );
        if flow_share_exceeded || buffer_exceeded {
            // #710: attribute the drop to the specific admission-path
            // reason. `flow_share_exceeded` is checked first so that
            // when both caps trip simultaneously, the root cause
            // (per-flow bucket saturation under SFQ collision / cap
            // undersizing) is counted rather than the buffer cap — the
            // buffer-cap hit is a symptom downstream of flow-share
            // admission failing to throttle the flow.
            if flow_share_exceeded {
                queue.telemetry.drop_counters.admission_flow_share_drops = queue
                    .telemetry
                    .drop_counters
                    .admission_flow_share_drops
                    .wrapping_add(1);
            } else {
                queue.telemetry.drop_counters.admission_buffer_drops = queue
                    .telemetry
                    .drop_counters
                    .admission_buffer_drops
                    .wrapping_add(1);
            }
            let recycle = match &item {
                CoSPendingTxItem::Prepared(req) => Some((req.recycle, req.offset)),
                CoSPendingTxItem::Local(_) => None,
            };
            (false, queue.queue_id(), recycle)
        } else {
            let queue_was_empty = cos_queue_is_empty(queue);
            queue.hot.queued_bytes = queue.hot.queued_bytes.saturating_add(item_len);
            cos_queue_push_back(queue, item);
            accepted_exact = queue.config.exact;
            if queue_was_empty {
                root.nonempty_queues = root.nonempty_queues.saturating_add(1);
                root_became_nonempty = root_was_empty;
            }
            if !queue.hot.parked && !queue.hot.runnable {
                root.runnable_queues = root.runnable_queues.saturating_add(1);
            }
            if !queue.hot.parked {
                mark_cos_queue_runnable(queue);
            }
            (true, queue.queue_id(), None)
        }
    };
    if root_became_nonempty {
        binding.cos.cos_nonempty_interfaces = binding.cos.cos_nonempty_interfaces.saturating_add(1);
    }
    if accepted {
        if accepted_exact {
            publish_cos_exact_backlog(binding, egress_ifindex);
        }
        return Ok(());
    }
    if let Some((recycle, offset)) = recycle {
        recycle_cancelled_prepared_offset_with_shared(
            &mut binding.tx_pipeline.free_tx_frames,
            &mut binding.tx_pipeline.pending_fill_frames,
            shared_recycles.as_deref_mut(),
            binding.slot,
            recycle,
            offset,
        );
    }
    // #804: CoS admission overflow — NOT bound-pending. Pre-#804 this
    // site incremented `dbg_pending_overflow` which conflated it with
    // the bound-pending FIFO evict sites; the two are now tracked on
    // separate counters so operators can disambiguate CoS shaping
    // pressure from bound-pending pressure.
    binding.telemetry.dbg_cos_queue_overflow += 1;
    // #hb166 T-6(g): a CoS admission drop is DESIGNED shaping, not a TX
    // error. It is already attributed above to the dedicated per-reason
    // `admission_flow_share_drops` / `admission_buffer_drops` counters, so
    // do NOT also inflate the aggregate `tx_errors` (an operator reads a
    // saturated shaper as a fault) and do NOT allocate a per-drop
    // `set_error(format!())` String: under a sustained shaping-drop storm
    // this classify path runs once per excess packet (~1M allocs/sec), a
    // hot-path-allocation-rule violation (CLAUDE.md). `dbg_cos_queue_overflow`
    // (plain, non-allocating) keeps the #804 disambiguation signal.
    Ok(())
}

#[cfg(test)]
#[path = "cos_classify_tests.rs"]
mod tests;
